os: linux
arch: arm64-graviton2
dist: focal

sudo: required
language: go
services:
    - docker
    
before_script:
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - curl https://cli-assets.heroku.com/install.sh | sudo sh
    - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
    - make fmt && git diff --exit-code
    - make test 

script:
    - make push IMAGE_VERSION=latest

deploy:   
    provider: script
    script: 
        docker push registry.heroku.com/$HEROKU_APP/web;
        heroku container:release web --app $HEROKU_APP