apiVersion: v1
kind: Namespace
metadata:
  name: users-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
  namespace: users-service
  labels:
    app.kubernetes.io/name: "users-service"
    app.kubernetes.io/component: "main"
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: "users-service"
      app.kubernetes.io/component: "main"
  replicas: 3
  template:
    metadata:
      labels:
        app.kubernetes.io/name: "users-service"
        app.kubernetes.io/component: "main"
    spec:
      restartPolicy: Always
      containers:
      - name: matchmaker
        image: amikhailau/users-service:latest
        imagePullPolicy: Always
        ports:
          - containerPort: 8080
        resources:
          limits:
            memory: 500Mi
            cpu: 500m
          requests:
            memory: 10Mi
            cpu: 1m