// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/amikhailau/users-service/pkg/pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	query "github.com/infobloxopen/atlas-app-toolkit/query"
	_ "github.com/infobloxopen/protoc-gen-atlas-query-validate/options"
	_ "github.com/infobloxopen/protoc-gen-atlas-validate/options"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TODO: Structure your own protobuf messages. Each protocol buffer message is a
// small logical record of information, containing a series of name-value pairs.
type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{0}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type User struct {
	Id                   string       `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string       `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string       `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	Password             string       `protobuf:"bytes,4,opt,name=password,proto3" json:"password,omitempty"`
	Coins                int64        `protobuf:"varint,5,opt,name=coins,proto3" json:"coins,omitempty"`
	Gems                 int64        `protobuf:"varint,6,opt,name=gems,proto3" json:"gems,omitempty"`
	Items                []*StoreItem `protobuf:"bytes,7,rep,name=items,proto3" json:"items,omitempty"`
	Stats                *UserStats   `protobuf:"bytes,8,opt,name=stats,proto3" json:"stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *User) GetCoins() int64 {
	if m != nil {
		return m.Coins
	}
	return 0
}

func (m *User) GetGems() int64 {
	if m != nil {
		return m.Gems
	}
	return 0
}

func (m *User) GetItems() []*StoreItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *User) GetStats() *UserStats {
	if m != nil {
		return m.Stats
	}
	return nil
}

type CreateUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{2}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserResponse struct {
	Result               *User    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{3}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetResult() *User {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserRequest) Reset()         { *m = ReadUserRequest{} }
func (m *ReadUserRequest) String() string { return proto.CompactTextString(m) }
func (*ReadUserRequest) ProtoMessage()    {}
func (*ReadUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{4}
}

func (m *ReadUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserRequest.Unmarshal(m, b)
}
func (m *ReadUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserRequest.Marshal(b, m, deterministic)
}
func (m *ReadUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserRequest.Merge(m, src)
}
func (m *ReadUserRequest) XXX_Size() int {
	return xxx_messageInfo_ReadUserRequest.Size(m)
}
func (m *ReadUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserRequest proto.InternalMessageInfo

func (m *ReadUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadUserResponse struct {
	Result               *User    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserResponse) Reset()         { *m = ReadUserResponse{} }
func (m *ReadUserResponse) String() string { return proto.CompactTextString(m) }
func (*ReadUserResponse) ProtoMessage()    {}
func (*ReadUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{5}
}

func (m *ReadUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserResponse.Unmarshal(m, b)
}
func (m *ReadUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserResponse.Marshal(b, m, deterministic)
}
func (m *ReadUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserResponse.Merge(m, src)
}
func (m *ReadUserResponse) XXX_Size() int {
	return xxx_messageInfo_ReadUserResponse.Size(m)
}
func (m *ReadUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserResponse proto.InternalMessageInfo

func (m *ReadUserResponse) GetResult() *User {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{6}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *UpdateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UpdateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type UpdateUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{7}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

type DeleteUserRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{8}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{9}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

type ListUsersRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{10}
}

func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (m *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(m, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

func (m *ListUsersRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListUsersRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListUsersRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListUsersRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListUsersResponse struct {
	Results              []*User         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Page                 *query.PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{11}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetResults() []*User {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ListUsersResponse) GetPage() *query.PageInfo {
	if m != nil {
		return m.Page
	}
	return nil
}

type StoreItem struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Type                 int64    `protobuf:"varint,4,opt,name=type,proto3" json:"type,omitempty"`
	CoinsPrice           int64    `protobuf:"varint,5,opt,name=coins_price,json=coinsPrice,proto3" json:"coins_price,omitempty"`
	GemsPrice            int64    `protobuf:"varint,6,opt,name=gems_price,json=gemsPrice,proto3" json:"gems_price,omitempty"`
	Image                []byte   `protobuf:"bytes,7,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StoreItem) Reset()         { *m = StoreItem{} }
func (m *StoreItem) String() string { return proto.CompactTextString(m) }
func (*StoreItem) ProtoMessage()    {}
func (*StoreItem) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{12}
}

func (m *StoreItem) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StoreItem.Unmarshal(m, b)
}
func (m *StoreItem) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StoreItem.Marshal(b, m, deterministic)
}
func (m *StoreItem) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StoreItem.Merge(m, src)
}
func (m *StoreItem) XXX_Size() int {
	return xxx_messageInfo_StoreItem.Size(m)
}
func (m *StoreItem) XXX_DiscardUnknown() {
	xxx_messageInfo_StoreItem.DiscardUnknown(m)
}

var xxx_messageInfo_StoreItem proto.InternalMessageInfo

func (m *StoreItem) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *StoreItem) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *StoreItem) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *StoreItem) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *StoreItem) GetCoinsPrice() int64 {
	if m != nil {
		return m.CoinsPrice
	}
	return 0
}

func (m *StoreItem) GetGemsPrice() int64 {
	if m != nil {
		return m.GemsPrice
	}
	return 0
}

func (m *StoreItem) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type CreateStoreItemRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Type                 int64    `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`
	CoinsPrice           int64    `protobuf:"varint,4,opt,name=coins_price,json=coinsPrice,proto3" json:"coins_price,omitempty"`
	GemsPrice            int64    `protobuf:"varint,5,opt,name=gems_price,json=gemsPrice,proto3" json:"gems_price,omitempty"`
	Image                []byte   `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateStoreItemRequest) Reset()         { *m = CreateStoreItemRequest{} }
func (m *CreateStoreItemRequest) String() string { return proto.CompactTextString(m) }
func (*CreateStoreItemRequest) ProtoMessage()    {}
func (*CreateStoreItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{13}
}

func (m *CreateStoreItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStoreItemRequest.Unmarshal(m, b)
}
func (m *CreateStoreItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStoreItemRequest.Marshal(b, m, deterministic)
}
func (m *CreateStoreItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStoreItemRequest.Merge(m, src)
}
func (m *CreateStoreItemRequest) XXX_Size() int {
	return xxx_messageInfo_CreateStoreItemRequest.Size(m)
}
func (m *CreateStoreItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStoreItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStoreItemRequest proto.InternalMessageInfo

func (m *CreateStoreItemRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateStoreItemRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateStoreItemRequest) GetType() int64 {
	if m != nil {
		return m.Type
	}
	return 0
}

func (m *CreateStoreItemRequest) GetCoinsPrice() int64 {
	if m != nil {
		return m.CoinsPrice
	}
	return 0
}

func (m *CreateStoreItemRequest) GetGemsPrice() int64 {
	if m != nil {
		return m.GemsPrice
	}
	return 0
}

func (m *CreateStoreItemRequest) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type CreateStoreItemResponse struct {
	Result               *StoreItem `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *CreateStoreItemResponse) Reset()         { *m = CreateStoreItemResponse{} }
func (m *CreateStoreItemResponse) String() string { return proto.CompactTextString(m) }
func (*CreateStoreItemResponse) ProtoMessage()    {}
func (*CreateStoreItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{14}
}

func (m *CreateStoreItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateStoreItemResponse.Unmarshal(m, b)
}
func (m *CreateStoreItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateStoreItemResponse.Marshal(b, m, deterministic)
}
func (m *CreateStoreItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateStoreItemResponse.Merge(m, src)
}
func (m *CreateStoreItemResponse) XXX_Size() int {
	return xxx_messageInfo_CreateStoreItemResponse.Size(m)
}
func (m *CreateStoreItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateStoreItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateStoreItemResponse proto.InternalMessageInfo

func (m *CreateStoreItemResponse) GetResult() *StoreItem {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadStoreItemRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadStoreItemRequest) Reset()         { *m = ReadStoreItemRequest{} }
func (m *ReadStoreItemRequest) String() string { return proto.CompactTextString(m) }
func (*ReadStoreItemRequest) ProtoMessage()    {}
func (*ReadStoreItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{15}
}

func (m *ReadStoreItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadStoreItemRequest.Unmarshal(m, b)
}
func (m *ReadStoreItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadStoreItemRequest.Marshal(b, m, deterministic)
}
func (m *ReadStoreItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadStoreItemRequest.Merge(m, src)
}
func (m *ReadStoreItemRequest) XXX_Size() int {
	return xxx_messageInfo_ReadStoreItemRequest.Size(m)
}
func (m *ReadStoreItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadStoreItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadStoreItemRequest proto.InternalMessageInfo

func (m *ReadStoreItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type ReadStoreItemResponse struct {
	Result               *StoreItem `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReadStoreItemResponse) Reset()         { *m = ReadStoreItemResponse{} }
func (m *ReadStoreItemResponse) String() string { return proto.CompactTextString(m) }
func (*ReadStoreItemResponse) ProtoMessage()    {}
func (*ReadStoreItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{16}
}

func (m *ReadStoreItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadStoreItemResponse.Unmarshal(m, b)
}
func (m *ReadStoreItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadStoreItemResponse.Marshal(b, m, deterministic)
}
func (m *ReadStoreItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadStoreItemResponse.Merge(m, src)
}
func (m *ReadStoreItemResponse) XXX_Size() int {
	return xxx_messageInfo_ReadStoreItemResponse.Size(m)
}
func (m *ReadStoreItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadStoreItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadStoreItemResponse proto.InternalMessageInfo

func (m *ReadStoreItemResponse) GetResult() *StoreItem {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateStoreItemRequest struct {
	Payload              *StoreItem            `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Fields               *field_mask.FieldMask `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateStoreItemRequest) Reset()         { *m = UpdateStoreItemRequest{} }
func (m *UpdateStoreItemRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateStoreItemRequest) ProtoMessage()    {}
func (*UpdateStoreItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{17}
}

func (m *UpdateStoreItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStoreItemRequest.Unmarshal(m, b)
}
func (m *UpdateStoreItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStoreItemRequest.Marshal(b, m, deterministic)
}
func (m *UpdateStoreItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStoreItemRequest.Merge(m, src)
}
func (m *UpdateStoreItemRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateStoreItemRequest.Size(m)
}
func (m *UpdateStoreItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStoreItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStoreItemRequest proto.InternalMessageInfo

func (m *UpdateStoreItemRequest) GetPayload() *StoreItem {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UpdateStoreItemRequest) GetFields() *field_mask.FieldMask {
	if m != nil {
		return m.Fields
	}
	return nil
}

type UpdateStoreItemResponse struct {
	Result               *StoreItem `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateStoreItemResponse) Reset()         { *m = UpdateStoreItemResponse{} }
func (m *UpdateStoreItemResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateStoreItemResponse) ProtoMessage()    {}
func (*UpdateStoreItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{18}
}

func (m *UpdateStoreItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateStoreItemResponse.Unmarshal(m, b)
}
func (m *UpdateStoreItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateStoreItemResponse.Marshal(b, m, deterministic)
}
func (m *UpdateStoreItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateStoreItemResponse.Merge(m, src)
}
func (m *UpdateStoreItemResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateStoreItemResponse.Size(m)
}
func (m *UpdateStoreItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateStoreItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateStoreItemResponse proto.InternalMessageInfo

func (m *UpdateStoreItemResponse) GetResult() *StoreItem {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteStoreItemRequest struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStoreItemRequest) Reset()         { *m = DeleteStoreItemRequest{} }
func (m *DeleteStoreItemRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteStoreItemRequest) ProtoMessage()    {}
func (*DeleteStoreItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{19}
}

func (m *DeleteStoreItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStoreItemRequest.Unmarshal(m, b)
}
func (m *DeleteStoreItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStoreItemRequest.Marshal(b, m, deterministic)
}
func (m *DeleteStoreItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStoreItemRequest.Merge(m, src)
}
func (m *DeleteStoreItemRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteStoreItemRequest.Size(m)
}
func (m *DeleteStoreItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStoreItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStoreItemRequest proto.InternalMessageInfo

func (m *DeleteStoreItemRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type DeleteStoreItemResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteStoreItemResponse) Reset()         { *m = DeleteStoreItemResponse{} }
func (m *DeleteStoreItemResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteStoreItemResponse) ProtoMessage()    {}
func (*DeleteStoreItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{20}
}

func (m *DeleteStoreItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteStoreItemResponse.Unmarshal(m, b)
}
func (m *DeleteStoreItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteStoreItemResponse.Marshal(b, m, deterministic)
}
func (m *DeleteStoreItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteStoreItemResponse.Merge(m, src)
}
func (m *DeleteStoreItemResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteStoreItemResponse.Size(m)
}
func (m *DeleteStoreItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteStoreItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteStoreItemResponse proto.InternalMessageInfo

type ListStoreItemsRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListStoreItemsRequest) Reset()         { *m = ListStoreItemsRequest{} }
func (m *ListStoreItemsRequest) String() string { return proto.CompactTextString(m) }
func (*ListStoreItemsRequest) ProtoMessage()    {}
func (*ListStoreItemsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{21}
}

func (m *ListStoreItemsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStoreItemsRequest.Unmarshal(m, b)
}
func (m *ListStoreItemsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStoreItemsRequest.Marshal(b, m, deterministic)
}
func (m *ListStoreItemsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStoreItemsRequest.Merge(m, src)
}
func (m *ListStoreItemsRequest) XXX_Size() int {
	return xxx_messageInfo_ListStoreItemsRequest.Size(m)
}
func (m *ListStoreItemsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStoreItemsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListStoreItemsRequest proto.InternalMessageInfo

func (m *ListStoreItemsRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListStoreItemsRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListStoreItemsRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListStoreItemsRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListStoreItemsResponse struct {
	Results              []*StoreItem    `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Page                 *query.PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListStoreItemsResponse) Reset()         { *m = ListStoreItemsResponse{} }
func (m *ListStoreItemsResponse) String() string { return proto.CompactTextString(m) }
func (*ListStoreItemsResponse) ProtoMessage()    {}
func (*ListStoreItemsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{22}
}

func (m *ListStoreItemsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListStoreItemsResponse.Unmarshal(m, b)
}
func (m *ListStoreItemsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListStoreItemsResponse.Marshal(b, m, deterministic)
}
func (m *ListStoreItemsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListStoreItemsResponse.Merge(m, src)
}
func (m *ListStoreItemsResponse) XXX_Size() int {
	return xxx_messageInfo_ListStoreItemsResponse.Size(m)
}
func (m *ListStoreItemsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListStoreItemsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListStoreItemsResponse proto.InternalMessageInfo

func (m *ListStoreItemsResponse) GetResults() []*StoreItem {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ListStoreItemsResponse) GetPage() *query.PageInfo {
	if m != nil {
		return m.Page
	}
	return nil
}

type UserStats struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Games                int64    `protobuf:"varint,2,opt,name=games,proto3" json:"games,omitempty"`
	Wins                 int64    `protobuf:"varint,3,opt,name=wins,proto3" json:"wins,omitempty"`
	Top5                 int64    `protobuf:"varint,4,opt,name=top5,proto3" json:"top5,omitempty"`
	Kills                int64    `protobuf:"varint,5,opt,name=kills,proto3" json:"kills,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserStats) Reset()         { *m = UserStats{} }
func (m *UserStats) String() string { return proto.CompactTextString(m) }
func (*UserStats) ProtoMessage()    {}
func (*UserStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{23}
}

func (m *UserStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserStats.Unmarshal(m, b)
}
func (m *UserStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserStats.Marshal(b, m, deterministic)
}
func (m *UserStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserStats.Merge(m, src)
}
func (m *UserStats) XXX_Size() int {
	return xxx_messageInfo_UserStats.Size(m)
}
func (m *UserStats) XXX_DiscardUnknown() {
	xxx_messageInfo_UserStats.DiscardUnknown(m)
}

var xxx_messageInfo_UserStats proto.InternalMessageInfo

func (m *UserStats) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserStats) GetGames() int64 {
	if m != nil {
		return m.Games
	}
	return 0
}

func (m *UserStats) GetWins() int64 {
	if m != nil {
		return m.Wins
	}
	return 0
}

func (m *UserStats) GetTop5() int64 {
	if m != nil {
		return m.Top5
	}
	return 0
}

func (m *UserStats) GetKills() int64 {
	if m != nil {
		return m.Kills
	}
	return 0
}

type ReadUserStatsRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserStatsRequest) Reset()         { *m = ReadUserStatsRequest{} }
func (m *ReadUserStatsRequest) String() string { return proto.CompactTextString(m) }
func (*ReadUserStatsRequest) ProtoMessage()    {}
func (*ReadUserStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{24}
}

func (m *ReadUserStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserStatsRequest.Unmarshal(m, b)
}
func (m *ReadUserStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserStatsRequest.Marshal(b, m, deterministic)
}
func (m *ReadUserStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserStatsRequest.Merge(m, src)
}
func (m *ReadUserStatsRequest) XXX_Size() int {
	return xxx_messageInfo_ReadUserStatsRequest.Size(m)
}
func (m *ReadUserStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserStatsRequest proto.InternalMessageInfo

func (m *ReadUserStatsRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type ReadUserStatsResponse struct {
	Result               *UserStats `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ReadUserStatsResponse) Reset()         { *m = ReadUserStatsResponse{} }
func (m *ReadUserStatsResponse) String() string { return proto.CompactTextString(m) }
func (*ReadUserStatsResponse) ProtoMessage()    {}
func (*ReadUserStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{25}
}

func (m *ReadUserStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserStatsResponse.Unmarshal(m, b)
}
func (m *ReadUserStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserStatsResponse.Marshal(b, m, deterministic)
}
func (m *ReadUserStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserStatsResponse.Merge(m, src)
}
func (m *ReadUserStatsResponse) XXX_Size() int {
	return xxx_messageInfo_ReadUserStatsResponse.Size(m)
}
func (m *ReadUserStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserStatsResponse proto.InternalMessageInfo

func (m *ReadUserStatsResponse) GetResult() *UserStats {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateUserStatsRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	AddGames             int64    `protobuf:"varint,2,opt,name=add_games,json=addGames,proto3" json:"add_games,omitempty"`
	AddWins              int64    `protobuf:"varint,3,opt,name=add_wins,json=addWins,proto3" json:"add_wins,omitempty"`
	AddTop5              int64    `protobuf:"varint,4,opt,name=add_top5,json=addTop5,proto3" json:"add_top5,omitempty"`
	AddKills             int64    `protobuf:"varint,5,opt,name=add_kills,json=addKills,proto3" json:"add_kills,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserStatsRequest) Reset()         { *m = UpdateUserStatsRequest{} }
func (m *UpdateUserStatsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserStatsRequest) ProtoMessage()    {}
func (*UpdateUserStatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{26}
}

func (m *UpdateUserStatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserStatsRequest.Unmarshal(m, b)
}
func (m *UpdateUserStatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserStatsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserStatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserStatsRequest.Merge(m, src)
}
func (m *UpdateUserStatsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserStatsRequest.Size(m)
}
func (m *UpdateUserStatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserStatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserStatsRequest proto.InternalMessageInfo

func (m *UpdateUserStatsRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *UpdateUserStatsRequest) GetAddGames() int64 {
	if m != nil {
		return m.AddGames
	}
	return 0
}

func (m *UpdateUserStatsRequest) GetAddWins() int64 {
	if m != nil {
		return m.AddWins
	}
	return 0
}

func (m *UpdateUserStatsRequest) GetAddTop5() int64 {
	if m != nil {
		return m.AddTop5
	}
	return 0
}

func (m *UpdateUserStatsRequest) GetAddKills() int64 {
	if m != nil {
		return m.AddKills
	}
	return 0
}

type UpdateUserStatsResponse struct {
	Result               *UserStats `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *UpdateUserStatsResponse) Reset()         { *m = UpdateUserStatsResponse{} }
func (m *UpdateUserStatsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserStatsResponse) ProtoMessage()    {}
func (*UpdateUserStatsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{27}
}

func (m *UpdateUserStatsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserStatsResponse.Unmarshal(m, b)
}
func (m *UpdateUserStatsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserStatsResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserStatsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserStatsResponse.Merge(m, src)
}
func (m *UpdateUserStatsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserStatsResponse.Size(m)
}
func (m *UpdateUserStatsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserStatsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserStatsResponse proto.InternalMessageInfo

func (m *UpdateUserStatsResponse) GetResult() *UserStats {
	if m != nil {
		return m.Result
	}
	return nil
}

type News struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Date                 *timestamp.Timestamp `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Title                string               `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string               `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Image                []byte               `protobuf:"bytes,5,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *News) Reset()         { *m = News{} }
func (m *News) String() string { return proto.CompactTextString(m) }
func (*News) ProtoMessage()    {}
func (*News) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{28}
}

func (m *News) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_News.Unmarshal(m, b)
}
func (m *News) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_News.Marshal(b, m, deterministic)
}
func (m *News) XXX_Merge(src proto.Message) {
	xxx_messageInfo_News.Merge(m, src)
}
func (m *News) XXX_Size() int {
	return xxx_messageInfo_News.Size(m)
}
func (m *News) XXX_DiscardUnknown() {
	xxx_messageInfo_News.DiscardUnknown(m)
}

var xxx_messageInfo_News proto.InternalMessageInfo

func (m *News) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *News) GetDate() *timestamp.Timestamp {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *News) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *News) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *News) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type CreateNewsRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Image                []byte   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewsRequest) Reset()         { *m = CreateNewsRequest{} }
func (m *CreateNewsRequest) String() string { return proto.CompactTextString(m) }
func (*CreateNewsRequest) ProtoMessage()    {}
func (*CreateNewsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{29}
}

func (m *CreateNewsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewsRequest.Unmarshal(m, b)
}
func (m *CreateNewsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewsRequest.Marshal(b, m, deterministic)
}
func (m *CreateNewsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewsRequest.Merge(m, src)
}
func (m *CreateNewsRequest) XXX_Size() int {
	return xxx_messageInfo_CreateNewsRequest.Size(m)
}
func (m *CreateNewsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewsRequest proto.InternalMessageInfo

func (m *CreateNewsRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *CreateNewsRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *CreateNewsRequest) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type CreateNewsResponse struct {
	Result               *News    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateNewsResponse) Reset()         { *m = CreateNewsResponse{} }
func (m *CreateNewsResponse) String() string { return proto.CompactTextString(m) }
func (*CreateNewsResponse) ProtoMessage()    {}
func (*CreateNewsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{30}
}

func (m *CreateNewsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateNewsResponse.Unmarshal(m, b)
}
func (m *CreateNewsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateNewsResponse.Marshal(b, m, deterministic)
}
func (m *CreateNewsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateNewsResponse.Merge(m, src)
}
func (m *CreateNewsResponse) XXX_Size() int {
	return xxx_messageInfo_CreateNewsResponse.Size(m)
}
func (m *CreateNewsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateNewsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateNewsResponse proto.InternalMessageInfo

func (m *CreateNewsResponse) GetResult() *News {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadNewsRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadNewsRequest) Reset()         { *m = ReadNewsRequest{} }
func (m *ReadNewsRequest) String() string { return proto.CompactTextString(m) }
func (*ReadNewsRequest) ProtoMessage()    {}
func (*ReadNewsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{31}
}

func (m *ReadNewsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadNewsRequest.Unmarshal(m, b)
}
func (m *ReadNewsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadNewsRequest.Marshal(b, m, deterministic)
}
func (m *ReadNewsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadNewsRequest.Merge(m, src)
}
func (m *ReadNewsRequest) XXX_Size() int {
	return xxx_messageInfo_ReadNewsRequest.Size(m)
}
func (m *ReadNewsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadNewsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadNewsRequest proto.InternalMessageInfo

func (m *ReadNewsRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

type ReadNewsResponse struct {
	Result               *News    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadNewsResponse) Reset()         { *m = ReadNewsResponse{} }
func (m *ReadNewsResponse) String() string { return proto.CompactTextString(m) }
func (*ReadNewsResponse) ProtoMessage()    {}
func (*ReadNewsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{32}
}

func (m *ReadNewsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadNewsResponse.Unmarshal(m, b)
}
func (m *ReadNewsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadNewsResponse.Marshal(b, m, deterministic)
}
func (m *ReadNewsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadNewsResponse.Merge(m, src)
}
func (m *ReadNewsResponse) XXX_Size() int {
	return xxx_messageInfo_ReadNewsResponse.Size(m)
}
func (m *ReadNewsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadNewsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadNewsResponse proto.InternalMessageInfo

func (m *ReadNewsResponse) GetResult() *News {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateNewsRequest struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Image                []byte   `protobuf:"bytes,3,opt,name=image,proto3" json:"image,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNewsRequest) Reset()         { *m = UpdateNewsRequest{} }
func (m *UpdateNewsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateNewsRequest) ProtoMessage()    {}
func (*UpdateNewsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{33}
}

func (m *UpdateNewsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNewsRequest.Unmarshal(m, b)
}
func (m *UpdateNewsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNewsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateNewsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNewsRequest.Merge(m, src)
}
func (m *UpdateNewsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateNewsRequest.Size(m)
}
func (m *UpdateNewsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNewsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNewsRequest proto.InternalMessageInfo

func (m *UpdateNewsRequest) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *UpdateNewsRequest) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *UpdateNewsRequest) GetImage() []byte {
	if m != nil {
		return m.Image
	}
	return nil
}

type UpdateNewsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateNewsResponse) Reset()         { *m = UpdateNewsResponse{} }
func (m *UpdateNewsResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateNewsResponse) ProtoMessage()    {}
func (*UpdateNewsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{34}
}

func (m *UpdateNewsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateNewsResponse.Unmarshal(m, b)
}
func (m *UpdateNewsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateNewsResponse.Marshal(b, m, deterministic)
}
func (m *UpdateNewsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateNewsResponse.Merge(m, src)
}
func (m *UpdateNewsResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateNewsResponse.Size(m)
}
func (m *UpdateNewsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateNewsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateNewsResponse proto.InternalMessageInfo

type ListNewsRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListNewsRequest) Reset()         { *m = ListNewsRequest{} }
func (m *ListNewsRequest) String() string { return proto.CompactTextString(m) }
func (*ListNewsRequest) ProtoMessage()    {}
func (*ListNewsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{35}
}

func (m *ListNewsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNewsRequest.Unmarshal(m, b)
}
func (m *ListNewsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNewsRequest.Marshal(b, m, deterministic)
}
func (m *ListNewsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNewsRequest.Merge(m, src)
}
func (m *ListNewsRequest) XXX_Size() int {
	return xxx_messageInfo_ListNewsRequest.Size(m)
}
func (m *ListNewsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNewsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListNewsRequest proto.InternalMessageInfo

func (m *ListNewsRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListNewsRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListNewsRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListNewsRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListNewsResponse struct {
	Results              []*News         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Page                 *query.PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListNewsResponse) Reset()         { *m = ListNewsResponse{} }
func (m *ListNewsResponse) String() string { return proto.CompactTextString(m) }
func (*ListNewsResponse) ProtoMessage()    {}
func (*ListNewsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{36}
}

func (m *ListNewsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListNewsResponse.Unmarshal(m, b)
}
func (m *ListNewsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListNewsResponse.Marshal(b, m, deterministic)
}
func (m *ListNewsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListNewsResponse.Merge(m, src)
}
func (m *ListNewsResponse) XXX_Size() int {
	return xxx_messageInfo_ListNewsResponse.Size(m)
}
func (m *ListNewsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListNewsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListNewsResponse proto.InternalMessageInfo

func (m *ListNewsResponse) GetResults() []*News {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ListNewsResponse) GetPage() *query.PageInfo {
	if m != nil {
		return m.Page
	}
	return nil
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "service.VersionResponse")
	proto.RegisterType((*User)(nil), "service.User")
	proto.RegisterType((*CreateUserRequest)(nil), "service.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "service.CreateUserResponse")
	proto.RegisterType((*ReadUserRequest)(nil), "service.ReadUserRequest")
	proto.RegisterType((*ReadUserResponse)(nil), "service.ReadUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "service.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "service.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "service.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "service.DeleteUserResponse")
	proto.RegisterType((*ListUsersRequest)(nil), "service.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "service.ListUsersResponse")
	proto.RegisterType((*StoreItem)(nil), "service.StoreItem")
	proto.RegisterType((*CreateStoreItemRequest)(nil), "service.CreateStoreItemRequest")
	proto.RegisterType((*CreateStoreItemResponse)(nil), "service.CreateStoreItemResponse")
	proto.RegisterType((*ReadStoreItemRequest)(nil), "service.ReadStoreItemRequest")
	proto.RegisterType((*ReadStoreItemResponse)(nil), "service.ReadStoreItemResponse")
	proto.RegisterType((*UpdateStoreItemRequest)(nil), "service.UpdateStoreItemRequest")
	proto.RegisterType((*UpdateStoreItemResponse)(nil), "service.UpdateStoreItemResponse")
	proto.RegisterType((*DeleteStoreItemRequest)(nil), "service.DeleteStoreItemRequest")
	proto.RegisterType((*DeleteStoreItemResponse)(nil), "service.DeleteStoreItemResponse")
	proto.RegisterType((*ListStoreItemsRequest)(nil), "service.ListStoreItemsRequest")
	proto.RegisterType((*ListStoreItemsResponse)(nil), "service.ListStoreItemsResponse")
	proto.RegisterType((*UserStats)(nil), "service.UserStats")
	proto.RegisterType((*ReadUserStatsRequest)(nil), "service.ReadUserStatsRequest")
	proto.RegisterType((*ReadUserStatsResponse)(nil), "service.ReadUserStatsResponse")
	proto.RegisterType((*UpdateUserStatsRequest)(nil), "service.UpdateUserStatsRequest")
	proto.RegisterType((*UpdateUserStatsResponse)(nil), "service.UpdateUserStatsResponse")
	proto.RegisterType((*News)(nil), "service.News")
	proto.RegisterType((*CreateNewsRequest)(nil), "service.CreateNewsRequest")
	proto.RegisterType((*CreateNewsResponse)(nil), "service.CreateNewsResponse")
	proto.RegisterType((*ReadNewsRequest)(nil), "service.ReadNewsRequest")
	proto.RegisterType((*ReadNewsResponse)(nil), "service.ReadNewsResponse")
	proto.RegisterType((*UpdateNewsRequest)(nil), "service.UpdateNewsRequest")
	proto.RegisterType((*UpdateNewsResponse)(nil), "service.UpdateNewsResponse")
	proto.RegisterType((*ListNewsRequest)(nil), "service.ListNewsRequest")
	proto.RegisterType((*ListNewsResponse)(nil), "service.ListNewsResponse")
}

func init() {
	proto.RegisterFile("github.com/amikhailau/users-service/pkg/pb/service.proto", fileDescriptor_b1742b9f6e5341e0)
}

var fileDescriptor_b1742b9f6e5341e0 = []byte{
	// 1774 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x58, 0x4b, 0x6f, 0xdb, 0xca,
	0x15, 0x0e, 0xf5, 0xf6, 0x91, 0x9f, 0x73, 0xfd, 0x90, 0x98, 0xeb, 0x58, 0x65, 0xdb, 0x7b, 0x05,
	0x37, 0x16, 0x2f, 0xd8, 0x5e, 0xe0, 0xd6, 0x59, 0xd5, 0x49, 0x1a, 0x24, 0x6d, 0x02, 0x83, 0xb6,
	0x53, 0x34, 0x40, 0xa1, 0x8c, 0xc5, 0xb1, 0x42, 0x98, 0x12, 0x19, 0x92, 0xb2, 0xa3, 0x06, 0xd9,
	0xb4, 0xcb, 0x74, 0xd7, 0x9f, 0xd0, 0xae, 0xbb, 0xae, 0xbd, 0xe9, 0x8f, 0x28, 0xba, 0x09, 0x9a,
	0x4d, 0xd1, 0xdf, 0x51, 0x14, 0xf3, 0x20, 0x35, 0x7c, 0x48, 0x76, 0x5c, 0x74, 0x93, 0x1d, 0x67,
	0xce, 0xe3, 0x9b, 0xf3, 0x9c, 0x33, 0x84, 0xef, 0xfa, 0x76, 0xf8, 0x6a, 0x74, 0xdc, 0xe9, 0xb9,
	0x03, 0x1d, 0x0f, 0xec, 0xd3, 0x57, 0xd8, 0x76, 0xf0, 0x48, 0x1f, 0x05, 0xc4, 0x0f, 0x76, 0x02,
	0xe2, 0x9f, 0xd9, 0x3d, 0xa2, 0x7b, 0xa7, 0x7d, 0xdd, 0x3b, 0xd6, 0xc5, 0xb2, 0xe3, 0xf9, 0x6e,
	0xe8, 0xa2, 0xaa, 0x58, 0xaa, 0xb7, 0xfb, 0xae, 0xdb, 0x77, 0x88, 0xce, 0xb6, 0x8f, 0x47, 0x27,
	0x3a, 0x19, 0x78, 0xe1, 0x98, 0x73, 0xa9, 0x5f, 0x0a, 0x22, 0xf6, 0x6c, 0x1d, 0x0f, 0x87, 0x6e,
	0x88, 0x43, 0xdb, 0x1d, 0x06, 0x82, 0xfa, 0x33, 0x09, 0x9d, 0x0c, 0xcf, 0xdc, 0xb1, 0xe7, 0xbb,
	0x6f, 0xc6, 0x5c, 0x53, 0x6f, 0xa7, 0x4f, 0x86, 0x3b, 0x67, 0xd8, 0xb1, 0x2d, 0x1c, 0x12, 0x3d,
	0xf3, 0x21, 0x54, 0xdc, 0x95, 0x98, 0x83, 0x73, 0xdc, 0xef, 0x13, 0x5f, 0x77, 0x3d, 0x06, 0x92,
	0x03, 0xb8, 0x2b, 0x01, 0xda, 0xc3, 0x13, 0xf7, 0xd8, 0x71, 0xdf, 0xb8, 0x1e, 0x19, 0xca, 0x90,
	0x7d, 0xd7, 0x1f, 0xc4, 0x2a, 0xe8, 0x42, 0xc8, 0xb6, 0xd2, 0x76, 0x9e, 0xd8, 0xc4, 0xb1, 0xba,
	0x03, 0x1c, 0x9c, 0x0a, 0x8e, 0xad, 0x34, 0x47, 0x68, 0x0f, 0x48, 0x10, 0xe2, 0x81, 0x27, 0x18,
	0x9e, 0x4c, 0x83, 0xc7, 0xa1, 0x83, 0x83, 0x1d, 0xec, 0x79, 0x3b, 0xa1, 0xeb, 0x3a, 0xa7, 0x76,
	0xa8, 0xbf, 0x1e, 0x11, 0x7f, 0xac, 0xf7, 0x5c, 0xc7, 0x21, 0x3d, 0x7a, 0x94, 0xae, 0xeb, 0x11,
	0x1f, 0x87, 0xae, 0x1f, 0x99, 0x72, 0x78, 0x0d, 0x53, 0xb8, 0x5a, 0xa6, 0x6a, 0xe2, 0xc9, 0xc8,
	0x34, 0xb6, 0xdd, 0x4d, 0xb9, 0xf3, 0xd9, 0xb5, 0xb5, 0x66, 0xf4, 0xb1, 0xed, 0x94, 0x3e, 0xed,
	0x47, 0xb0, 0xf4, 0x9c, 0xf8, 0x81, 0xed, 0x0e, 0x4d, 0x12, 0x78, 0xee, 0x30, 0x20, 0xa8, 0x01,
	0xd5, 0x33, 0xbe, 0xd5, 0x50, 0x5a, 0x4a, 0x7b, 0xce, 0x8c, 0x96, 0xda, 0x7f, 0x14, 0x28, 0x1d,
	0x05, 0xc4, 0x47, 0x77, 0xa0, 0x60, 0x5b, 0x9c, 0xba, 0xb7, 0x78, 0x79, 0xd1, 0x04, 0xa8, 0xa1,
	0xd2, 0xd1, 0xd1, 0xe3, 0x07, 0x6d, 0xc5, 0x2c, 0xd8, 0x16, 0x42, 0x50, 0x1a, 0xe2, 0x01, 0x69,
	0x14, 0x98, 0x3c, 0xfb, 0x46, 0xab, 0x50, 0x26, 0x03, 0x6c, 0x3b, 0x8d, 0x22, 0xdb, 0xe4, 0x0b,
	0xa4, 0x42, 0xcd, 0xc3, 0x41, 0x70, 0xee, 0xfa, 0x56, 0xa3, 0xc4, 0x08, 0xf1, 0x9a, 0x4a, 0xf4,
	0x5c, 0x7b, 0x18, 0x34, 0xca, 0x2d, 0xa5, 0x5d, 0x34, 0xf9, 0x82, 0xea, 0xee, 0x93, 0x41, 0xd0,
	0xa8, 0xb0, 0x4d, 0xf6, 0x8d, 0x0c, 0x28, 0xdb, 0x21, 0xdd, 0xac, 0xb6, 0x8a, 0xed, 0xba, 0x81,
	0x3a, 0x51, 0x29, 0x1c, 0x84, 0xae, 0x4f, 0x1e, 0x87, 0x64, 0xb0, 0x57, 0xbb, 0xbc, 0x68, 0x96,
	0xb4, 0xc2, 0x77, 0x8a, 0xc9, 0x59, 0x51, 0x1b, 0xca, 0x41, 0x88, 0xc3, 0xa0, 0x51, 0x6b, 0x29,
	0x09, 0x19, 0x6a, 0xe1, 0x01, 0xa5, 0x98, 0x9c, 0x61, 0x97, 0x89, 0xd6, 0x94, 0xd6, 0x2d, 0xed,
	0xd7, 0xb0, 0x72, 0xdf, 0x27, 0x38, 0x24, 0x94, 0xc7, 0x24, 0xaf, 0x47, 0x24, 0x08, 0x63, 0x63,
	0x95, 0x3c, 0x63, 0x0b, 0xd3, 0x8c, 0x2d, 0x26, 0x8d, 0xd5, 0xee, 0x01, 0x92, 0x55, 0x8b, 0x58,
	0xfc, 0x10, 0x2a, 0x3e, 0x09, 0x46, 0x4e, 0xc8, 0xb4, 0xd7, 0x8d, 0x85, 0xc4, 0x29, 0x4d, 0x41,
	0xd4, 0xbe, 0x07, 0x4b, 0x26, 0xc1, 0x96, 0x7c, 0xaa, 0xc5, 0x49, 0x88, 0x68, 0x48, 0xb4, 0x9f,
	0xc2, 0xf2, 0x84, 0xe5, 0xd3, 0xb4, 0x1f, 0xc0, 0xca, 0x91, 0x67, 0xa5, 0xac, 0x4e, 0xe9, 0xcf,
	0x0d, 0xf9, 0x2c, 0x7b, 0x57, 0x01, 0xc9, 0x4a, 0xf9, 0x89, 0xb4, 0xef, 0xc3, 0xca, 0x03, 0xe2,
	0x90, 0x99, 0x50, 0x54, 0x54, 0x66, 0x12, 0xa2, 0x1f, 0x15, 0x58, 0xfe, 0xa5, 0x1d, 0x84, 0x74,
	0x33, 0x88, 0x44, 0x75, 0xa8, 0x9c, 0xd8, 0x4e, 0x48, 0x7c, 0x61, 0xe1, 0x46, 0x27, 0x2a, 0x9a,
	0x0e, 0xf6, 0xec, 0xce, 0xcf, 0x19, 0xcd, 0x1e, 0xf6, 0x4d, 0xc1, 0x86, 0xbe, 0x81, 0x9a, 0xeb,
	0x5b, 0xc4, 0xef, 0x1e, 0x8f, 0x99, 0x29, 0x75, 0x63, 0x2d, 0x29, 0x72, 0xe0, 0xfa, 0x21, 0x15,
	0xa8, 0x32, 0xb6, 0xbd, 0x31, 0xfa, 0x09, 0x85, 0x20, 0x8e, 0x15, 0x30, 0x13, 0xeb, 0xc6, 0x97,
	0x69, 0x08, 0xe2, 0x58, 0x07, 0x44, 0x74, 0x09, 0x53, 0xf0, 0xa2, 0x6f, 0xa0, 0xe2, 0xe1, 0xbe,
	0x3d, 0xec, 0xb3, 0xac, 0xaf, 0x1b, 0x8d, 0xa4, 0xd4, 0x3e, 0xa5, 0x61, 0x2e, 0xc1, 0xf9, 0xb4,
	0x57, 0xb0, 0x22, 0x99, 0x27, 0x22, 0xf8, 0x35, 0x54, 0x79, 0x90, 0x82, 0x86, 0xc2, 0x52, 0x3f,
	0x15, 0xc2, 0x88, 0x8a, 0xb6, 0xa1, 0xe4, 0xe1, 0x3e, 0x11, 0x36, 0xad, 0x67, 0xd0, 0xc8, 0xe3,
	0xe1, 0x89, 0x6b, 0x32, 0x1e, 0xed, 0x1f, 0x0a, 0xcc, 0xc5, 0x85, 0x73, 0xa3, 0x5a, 0x6f, 0x41,
	0xdd, 0x22, 0x41, 0xcf, 0xb7, 0x59, 0xeb, 0x11, 0xb1, 0x97, 0xb7, 0xa8, 0x54, 0x38, 0xf6, 0x08,
	0xb3, 0xbe, 0x68, 0xb2, 0x6f, 0xb4, 0x05, 0x75, 0x56, 0xe2, 0x5d, 0xcf, 0xb7, 0x7b, 0x44, 0x54,
	0x3d, 0xb0, 0xad, 0x7d, 0xba, 0x83, 0x36, 0x01, 0x68, 0xb9, 0x0b, 0x3a, 0x6f, 0x00, 0x73, 0x74,
	0x87, 0x93, 0x57, 0xa1, 0x6c, 0x0f, 0xa8, 0x91, 0xd5, 0x96, 0xd2, 0x9e, 0x37, 0xf9, 0x42, 0xaa,
	0xde, 0xbf, 0x2a, 0xb0, 0xce, 0x6b, 0x2c, 0xb6, 0x6e, 0x56, 0x0d, 0xa7, 0x8c, 0x28, 0x4c, 0x37,
	0xa2, 0x38, 0xdd, 0x88, 0xd2, 0x15, 0x46, 0x94, 0xa7, 0x1a, 0x51, 0x91, 0x8c, 0xd0, 0x1e, 0xc2,
	0x46, 0xe6, 0xe4, 0x22, 0x05, 0xb6, 0x53, 0x45, 0x9c, 0xd3, 0xfc, 0xe2, 0x4a, 0xfe, 0x0a, 0x56,
	0x69, 0x13, 0xc8, 0x98, 0x9f, 0xae, 0xb0, 0xfb, 0xb0, 0x96, 0xe2, 0xbb, 0x01, 0xd8, 0x6f, 0x61,
	0x9d, 0x57, 0x78, 0x06, 0xee, 0x2e, 0x54, 0x3d, 0x3c, 0x76, 0x5c, 0x6c, 0xcd, 0x50, 0x13, 0xb1,
	0x20, 0x23, 0x2e, 0x30, 0x9e, 0xbc, 0x6a, 0x87, 0x5f, 0xe3, 0x9d, 0xe8, 0x1a, 0xe7, 0x35, 0xf6,
	0x14, 0x07, 0xa7, 0x51, 0x79, 0x51, 0x7f, 0x65, 0xb0, 0x6f, 0x60, 0x42, 0x1b, 0xd6, 0x79, 0xa7,
	0xb9, 0xd2, 0x63, 0x4d, 0xd8, 0xc8, 0x70, 0x8a, 0xc6, 0xf4, 0x2f, 0x05, 0xd6, 0x68, 0xe5, 0xc6,
	0x94, 0xcf, 0xb1, 0x3b, 0xf9, 0xb0, 0x9e, 0xb6, 0x51, 0xf8, 0xfb, 0x6e, 0xba, 0x45, 0xe5, 0x06,
	0xfb, 0x26, 0x7d, 0xea, 0xbd, 0x02, 0x73, 0xf1, 0x65, 0x8d, 0x5a, 0x71, 0x44, 0x8a, 0x7b, 0xcb,
	0x97, 0x17, 0xcd, 0x79, 0x00, 0x54, 0x09, 0x88, 0x6f, 0x63, 0x47, 0x74, 0xaa, 0x55, 0x28, 0xf7,
	0xf1, 0x80, 0xf0, 0x3c, 0x2a, 0x9a, 0x7c, 0x41, 0x8b, 0xf8, 0x9c, 0x0e, 0x19, 0xa2, 0x88, 0xcf,
	0xc5, 0x8c, 0x11, 0xba, 0xde, 0xb7, 0x71, 0x77, 0x72, 0xbd, 0x6f, 0xa9, 0xf4, 0xa9, 0xed, 0x38,
	0xf1, 0x34, 0xc2, 0x16, 0x52, 0x77, 0x31, 0x78, 0x6d, 0x4d, 0xa6, 0x07, 0x11, 0x64, 0x15, 0x6a,
	0x74, 0x5a, 0x97, 0xda, 0x4b, 0xbc, 0x8e, 0xea, 0x4c, 0x92, 0xb9, 0x32, 0x49, 0x27, 0xbc, 0x51,
	0x92, 0xfe, 0x59, 0x89, 0x0a, 0xed, 0x53, 0xb0, 0xd1, 0x6d, 0x98, 0xc3, 0x96, 0xd5, 0x95, 0x3d,
	0x52, 0xc3, 0x96, 0xf5, 0x88, 0x39, 0xa5, 0x09, 0xf4, 0xbb, 0x2b, 0x39, 0xa6, 0x8a, 0x2d, 0xeb,
	0x57, 0xd4, 0x37, 0x82, 0x24, 0xf9, 0x87, 0x92, 0x0e, 0xa9, 0x8b, 0x84, 0x4a, 0xd9, 0x4d, 0x94,
	0xf7, 0x17, 0x74, 0x3d, 0x29, 0xc9, 0xff, 0xcd, 0xda, 0xbf, 0x28, 0x50, 0x7a, 0x46, 0xce, 0x83,
	0x2b, 0xef, 0xa5, 0x0e, 0x94, 0x28, 0xda, 0xd4, 0xa6, 0x71, 0x18, 0xcd, 0xfe, 0x26, 0xe3, 0xa3,
	0xf1, 0x0d, 0xed, 0xd0, 0x21, 0xd1, 0x7c, 0xca, 0x16, 0xe9, 0x4b, 0xa0, 0x94, 0xbd, 0x04, 0xe2,
	0x86, 0x5d, 0xce, 0xbf, 0x75, 0x70, 0x34, 0x33, 0xd2, 0x53, 0x47, 0x81, 0x89, 0xc1, 0x94, 0x19,
	0x60, 0x85, 0x19, 0x60, 0x45, 0xf9, 0x76, 0x88, 0x67, 0x47, 0x0e, 0x71, 0xe5, 0x74, 0xc7, 0xd8,
	0x22, 0x87, 0x7e, 0xcd, 0x67, 0xc7, 0x2b, 0x4f, 0x17, 0x4d, 0x90, 0x37, 0xc1, 0xc0, 0xd1, 0x04,
	0xf9, 0xff, 0xf3, 0x41, 0x3c, 0x4f, 0xca, 0xe7, 0xd3, 0xfe, 0xa9, 0xc0, 0x12, 0xed, 0x4b, 0x32,
	0xee, 0x67, 0xd4, 0x75, 0xfb, 0x7c, 0xe4, 0x4d, 0x84, 0x64, 0xc6, 0x48, 0xc8, 0xf8, 0x6e, 0xd2,
	0x6a, 0x8d, 0x97, 0x30, 0xcf, 0x06, 0xcf, 0x03, 0xae, 0x09, 0xed, 0x03, 0x3c, 0x22, 0xa1, 0x78,
	0x39, 0xa2, 0xf5, 0x4c, 0x71, 0x3d, 0x1c, 0x78, 0xe1, 0x58, 0x6d, 0xc4, 0xc8, 0xa9, 0x37, 0xa6,
	0xb6, 0xfc, 0xbb, 0xbf, 0xff, 0xfb, 0x8f, 0x05, 0x40, 0x35, 0x5d, 0xbc, 0x2d, 0x8d, 0x8f, 0x45,
	0x28, 0x33, 0x08, 0x74, 0x08, 0x15, 0x9e, 0xcd, 0x48, 0x8d, 0xe5, 0x33, 0xaf, 0x2e, 0xf5, 0x76,
	0x2e, 0x4d, 0xa8, 0x5f, 0x61, 0xea, 0xeb, 0x5a, 0x85, 0xff, 0x28, 0xd9, 0x55, 0xb6, 0xd1, 0x3e,
	0x94, 0x68, 0xf6, 0xa2, 0xc9, 0x99, 0x52, 0x2f, 0x26, 0xb5, 0x99, 0x43, 0x11, 0xfa, 0xbe, 0x60,
	0xfa, 0x16, 0x50, 0x9d, 0xeb, 0xd3, 0xdf, 0xda, 0xd6, 0x3b, 0xf4, 0x1a, 0x2a, 0x3c, 0xe3, 0xa4,
	0x73, 0x66, 0xde, 0x49, 0xd2, 0x39, 0x73, 0x9e, 0x3b, 0x9d, 0x0f, 0x7f, 0x6b, 0x16, 0x6a, 0xb7,
	0x98, 0x76, 0x4d, 0x95, 0xb5, 0xef, 0x2a, 0xdb, 0x2f, 0x96, 0x8d, 0xd4, 0x0e, 0x7a, 0x09, 0x15,
	0x3e, 0x65, 0x48, 0x90, 0x99, 0xf7, 0x92, 0x04, 0x99, 0xf3, 0x4c, 0xda, 0xbc, 0xbc, 0x68, 0x56,
	0xf8, 0x33, 0x9e, 0x1b, 0xb5, 0x9d, 0x30, 0xea, 0x29, 0x94, 0x68, 0x46, 0xa1, 0x89, 0x33, 0xd2,
	0x6f, 0x2a, 0x55, 0xcd, 0x23, 0x09, 0xed, 0x8b, 0x4c, 0x67, 0x0d, 0x09, 0xc7, 0xab, 0xa2, 0x0d,
	0x2e, 0xdf, 0x32, 0x3e, 0x94, 0x00, 0x26, 0xd3, 0x01, 0xb2, 0xe2, 0x20, 0x6f, 0xa5, 0x02, 0x99,
	0x1e, 0xb5, 0xd4, 0xd6, 0x74, 0x06, 0x81, 0xba, 0xc1, 0x50, 0x57, 0xb4, 0x79, 0x3d, 0xa0, 0xb4,
	0x2e, 0x7b, 0xe0, 0x73, 0x7f, 0xf1, 0xa0, 0x6f, 0x26, 0x42, 0x9b, 0x41, 0xb8, 0x33, 0x8d, 0x2c,
	0xf4, 0x37, 0x99, 0xfe, 0x2f, 0xd0, 0x8a, 0xac, 0x9f, 0xfb, 0xeb, 0x4f, 0x4a, 0x9c, 0x05, 0x5b,
	0xa9, 0x48, 0xcf, 0x30, 0x64, 0xca, 0x6c, 0xaa, 0x3d, 0x97, 0xf2, 0xe1, 0x89, 0xda, 0x4c, 0xc2,
	0x89, 0x79, 0xb8, 0x43, 0x73, 0x21, 0x1a, 0x8e, 0x5f, 0xfc, 0xc0, 0xb8, 0x06, 0x17, 0x1a, 0xc5,
	0x79, 0xb3, 0x95, 0xca, 0x8d, 0x19, 0x87, 0x9c, 0x36, 0xcf, 0xb6, 0x2f, 0x2f, 0x9a, 0x75, 0xe9,
	0x85, 0xc8, 0x9d, 0xb3, 0x9d, 0xe3, 0x9c, 0xdf, 0x88, 0x64, 0xba, 0x93, 0xc8, 0x98, 0xcc, 0x1c,
	0xac, 0x6e, 0x4d, 0xa5, 0x0b, 0xc8, 0x55, 0x86, 0xb1, 0x88, 0x12, 0x01, 0x96, 0x92, 0xeb, 0x7d,
	0x01, 0x80, 0xf7, 0x27, 0x36, 0x0a, 0x5a, 0x50, 0x7b, 0x44, 0x42, 0xfe, 0xbd, 0x99, 0xa9, 0x6a,
	0x79, 0x42, 0x4a, 0x85, 0x3e, 0x33, 0x9a, 0x24, 0x42, 0x8f, 0xc3, 0x40, 0x7f, 0x1b, 0xcd, 0x4f,
	0xef, 0xd0, 0x1f, 0x14, 0xa8, 0x47, 0x81, 0xa4, 0x48, 0x5b, 0x39, 0x95, 0x9e, 0xc0, 0x6a, 0x4d,
	0x67, 0x10, 0x68, 0xbb, 0x52, 0xfc, 0x3b, 0x6a, 0x16, 0x93, 0x76, 0x85, 0x75, 0x23, 0x77, 0x5f,
	0xf2, 0xc6, 0xef, 0x8b, 0x50, 0xa7, 0xad, 0x3e, 0x6a, 0xd6, 0x07, 0x53, 0x1b, 0xaa, 0x74, 0x2d,
	0x66, 0x1a, 0x6a, 0xe2, 0x1e, 0x15, 0xfd, 0x5a, 0x2b, 0xeb, 0x43, 0x72, 0xce, 0x4a, 0xcb, 0xcc,
	0xed, 0xa7, 0xb2, 0xc2, 0x66, 0x0e, 0x45, 0xa8, 0x5b, 0x63, 0xea, 0x96, 0xd0, 0x02, 0x53, 0xa7,
	0xbf, 0x65, 0x57, 0xff, 0x3b, 0x9a, 0xa6, 0x53, 0x3a, 0x6a, 0xfe, 0x41, 0x73, 0x2e, 0x7c, 0x43,
	0xf2, 0xe0, 0x57, 0x6a, 0x52, 0x3f, 0xf5, 0x1e, 0x32, 0x32, 0x7b, 0xe8, 0x89, 0x48, 0xd3, 0x46,
	0x22, 0x0d, 0xf3, 0x4d, 0x49, 0x5f, 0xb7, 0xda, 0x02, 0x83, 0xaa, 0x22, 0xee, 0x99, 0x49, 0x14,
	0xf6, 0xf4, 0x17, 0x3b, 0xd7, 0xff, 0x77, 0x7f, 0xcf, 0x3b, 0x3e, 0xae, 0xb0, 0xdb, 0xf3, 0xc7,
	0xff, 0x0d, 0x00, 0x00, 0xff, 0xff, 0xb4, 0xdb, 0x79, 0x6d, 0xf3, 0x17, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersServiceClient interface {
	GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type usersServiceClient struct {
	cc *grpc.ClientConn
}

func NewUsersServiceClient(cc *grpc.ClientConn) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/service.UsersService/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the server API for UsersService service.
type UsersServiceServer interface {
	GetVersion(context.Context, *empty.Empty) (*VersionResponse, error)
}

func RegisterUsersServiceServer(s *grpc.Server, srv UsersServiceServer) {
	s.RegisterService(&_UsersService_serviceDesc, srv)
}

func _UsersService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.UsersService/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetVersion(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _UsersService_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/amikhailau/users-service/pkg/pb/service.proto",
}

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersClient interface {
	Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	Read(ctx context.Context, in *ReadUserRequest, opts ...grpc.CallOption) (*ReadUserResponse, error)
	Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	Delete(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	List(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/service.Users/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Read(ctx context.Context, in *ReadUserRequest, opts ...grpc.CallOption) (*ReadUserResponse, error) {
	out := new(ReadUserResponse)
	err := c.cc.Invoke(ctx, "/service.Users/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/service.Users/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Delete(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/service.Users/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) List(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/service.Users/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
type UsersServer interface {
	Create(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	Read(context.Context, *ReadUserRequest) (*ReadUserResponse, error)
	Update(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	Delete(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	List(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Users/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Create(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Users/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Read(ctx, req.(*ReadUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Users/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Update(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Users/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Delete(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Users/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).List(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Users_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Users_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Users_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Users_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Users_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/amikhailau/users-service/pkg/pb/service.proto",
}

// StoreItemsClient is the client API for StoreItems service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type StoreItemsClient interface {
	Create(ctx context.Context, in *CreateStoreItemRequest, opts ...grpc.CallOption) (*CreateStoreItemResponse, error)
	Read(ctx context.Context, in *ReadStoreItemRequest, opts ...grpc.CallOption) (*ReadStoreItemResponse, error)
	Update(ctx context.Context, in *UpdateStoreItemRequest, opts ...grpc.CallOption) (*UpdateStoreItemResponse, error)
	Delete(ctx context.Context, in *DeleteStoreItemRequest, opts ...grpc.CallOption) (*DeleteStoreItemResponse, error)
	List(ctx context.Context, in *ListStoreItemsRequest, opts ...grpc.CallOption) (*ListStoreItemsResponse, error)
}

type storeItemsClient struct {
	cc *grpc.ClientConn
}

func NewStoreItemsClient(cc *grpc.ClientConn) StoreItemsClient {
	return &storeItemsClient{cc}
}

func (c *storeItemsClient) Create(ctx context.Context, in *CreateStoreItemRequest, opts ...grpc.CallOption) (*CreateStoreItemResponse, error) {
	out := new(CreateStoreItemResponse)
	err := c.cc.Invoke(ctx, "/service.StoreItems/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeItemsClient) Read(ctx context.Context, in *ReadStoreItemRequest, opts ...grpc.CallOption) (*ReadStoreItemResponse, error) {
	out := new(ReadStoreItemResponse)
	err := c.cc.Invoke(ctx, "/service.StoreItems/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeItemsClient) Update(ctx context.Context, in *UpdateStoreItemRequest, opts ...grpc.CallOption) (*UpdateStoreItemResponse, error) {
	out := new(UpdateStoreItemResponse)
	err := c.cc.Invoke(ctx, "/service.StoreItems/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeItemsClient) Delete(ctx context.Context, in *DeleteStoreItemRequest, opts ...grpc.CallOption) (*DeleteStoreItemResponse, error) {
	out := new(DeleteStoreItemResponse)
	err := c.cc.Invoke(ctx, "/service.StoreItems/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storeItemsClient) List(ctx context.Context, in *ListStoreItemsRequest, opts ...grpc.CallOption) (*ListStoreItemsResponse, error) {
	out := new(ListStoreItemsResponse)
	err := c.cc.Invoke(ctx, "/service.StoreItems/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StoreItemsServer is the server API for StoreItems service.
type StoreItemsServer interface {
	Create(context.Context, *CreateStoreItemRequest) (*CreateStoreItemResponse, error)
	Read(context.Context, *ReadStoreItemRequest) (*ReadStoreItemResponse, error)
	Update(context.Context, *UpdateStoreItemRequest) (*UpdateStoreItemResponse, error)
	Delete(context.Context, *DeleteStoreItemRequest) (*DeleteStoreItemResponse, error)
	List(context.Context, *ListStoreItemsRequest) (*ListStoreItemsResponse, error)
}

func RegisterStoreItemsServer(s *grpc.Server, srv StoreItemsServer) {
	s.RegisterService(&_StoreItems_serviceDesc, srv)
}

func _StoreItems_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateStoreItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreItemsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.StoreItems/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreItemsServer).Create(ctx, req.(*CreateStoreItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreItems_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadStoreItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreItemsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.StoreItems/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreItemsServer).Read(ctx, req.(*ReadStoreItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreItems_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateStoreItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreItemsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.StoreItems/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreItemsServer).Update(ctx, req.(*UpdateStoreItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreItems_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteStoreItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreItemsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.StoreItems/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreItemsServer).Delete(ctx, req.(*DeleteStoreItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StoreItems_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListStoreItemsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StoreItemsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.StoreItems/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StoreItemsServer).List(ctx, req.(*ListStoreItemsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _StoreItems_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.StoreItems",
	HandlerType: (*StoreItemsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _StoreItems_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _StoreItems_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _StoreItems_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _StoreItems_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _StoreItems_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/amikhailau/users-service/pkg/pb/service.proto",
}

// UsersStatsClient is the client API for UsersStats service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersStatsClient interface {
	GetStats(ctx context.Context, in *ReadUserStatsRequest, opts ...grpc.CallOption) (*ReadUserStatsResponse, error)
	UpdateStats(ctx context.Context, in *UpdateUserStatsRequest, opts ...grpc.CallOption) (*UpdateUserStatsResponse, error)
}

type usersStatsClient struct {
	cc *grpc.ClientConn
}

func NewUsersStatsClient(cc *grpc.ClientConn) UsersStatsClient {
	return &usersStatsClient{cc}
}

func (c *usersStatsClient) GetStats(ctx context.Context, in *ReadUserStatsRequest, opts ...grpc.CallOption) (*ReadUserStatsResponse, error) {
	out := new(ReadUserStatsResponse)
	err := c.cc.Invoke(ctx, "/service.UsersStats/GetStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersStatsClient) UpdateStats(ctx context.Context, in *UpdateUserStatsRequest, opts ...grpc.CallOption) (*UpdateUserStatsResponse, error) {
	out := new(UpdateUserStatsResponse)
	err := c.cc.Invoke(ctx, "/service.UsersStats/UpdateStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersStatsServer is the server API for UsersStats service.
type UsersStatsServer interface {
	GetStats(context.Context, *ReadUserStatsRequest) (*ReadUserStatsResponse, error)
	UpdateStats(context.Context, *UpdateUserStatsRequest) (*UpdateUserStatsResponse, error)
}

func RegisterUsersStatsServer(s *grpc.Server, srv UsersStatsServer) {
	s.RegisterService(&_UsersStats_serviceDesc, srv)
}

func _UsersStats_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadUserStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersStatsServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.UsersStats/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersStatsServer).GetStats(ctx, req.(*ReadUserStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UsersStats_UpdateStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersStatsServer).UpdateStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.UsersStats/UpdateStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersStatsServer).UpdateStats(ctx, req.(*UpdateUserStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersStats_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.UsersStats",
	HandlerType: (*UsersStatsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetStats",
			Handler:    _UsersStats_GetStats_Handler,
		},
		{
			MethodName: "UpdateStats",
			Handler:    _UsersStats_UpdateStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/amikhailau/users-service/pkg/pb/service.proto",
}

// NewsServiceClient is the client API for NewsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NewsServiceClient interface {
	Create(ctx context.Context, in *CreateNewsRequest, opts ...grpc.CallOption) (*CreateNewsResponse, error)
	Read(ctx context.Context, in *ReadNewsRequest, opts ...grpc.CallOption) (*ReadNewsResponse, error)
	Update(ctx context.Context, in *UpdateNewsRequest, opts ...grpc.CallOption) (*UpdateNewsResponse, error)
	List(ctx context.Context, in *ListNewsRequest, opts ...grpc.CallOption) (*ListNewsResponse, error)
}

type newsServiceClient struct {
	cc *grpc.ClientConn
}

func NewNewsServiceClient(cc *grpc.ClientConn) NewsServiceClient {
	return &newsServiceClient{cc}
}

func (c *newsServiceClient) Create(ctx context.Context, in *CreateNewsRequest, opts ...grpc.CallOption) (*CreateNewsResponse, error) {
	out := new(CreateNewsResponse)
	err := c.cc.Invoke(ctx, "/service.NewsService/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsServiceClient) Read(ctx context.Context, in *ReadNewsRequest, opts ...grpc.CallOption) (*ReadNewsResponse, error) {
	out := new(ReadNewsResponse)
	err := c.cc.Invoke(ctx, "/service.NewsService/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsServiceClient) Update(ctx context.Context, in *UpdateNewsRequest, opts ...grpc.CallOption) (*UpdateNewsResponse, error) {
	out := new(UpdateNewsResponse)
	err := c.cc.Invoke(ctx, "/service.NewsService/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *newsServiceClient) List(ctx context.Context, in *ListNewsRequest, opts ...grpc.CallOption) (*ListNewsResponse, error) {
	out := new(ListNewsResponse)
	err := c.cc.Invoke(ctx, "/service.NewsService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NewsServiceServer is the server API for NewsService service.
type NewsServiceServer interface {
	Create(context.Context, *CreateNewsRequest) (*CreateNewsResponse, error)
	Read(context.Context, *ReadNewsRequest) (*ReadNewsResponse, error)
	Update(context.Context, *UpdateNewsRequest) (*UpdateNewsResponse, error)
	List(context.Context, *ListNewsRequest) (*ListNewsResponse, error)
}

func RegisterNewsServiceServer(s *grpc.Server, srv NewsServiceServer) {
	s.RegisterService(&_NewsService_serviceDesc, srv)
}

func _NewsService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.NewsService/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).Create(ctx, req.(*CreateNewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadNewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.NewsService/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).Read(ctx, req.(*ReadNewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.NewsService/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).Update(ctx, req.(*UpdateNewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NewsService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListNewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NewsServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.NewsService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NewsServiceServer).List(ctx, req.(*ListNewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NewsService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.NewsService",
	HandlerType: (*NewsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _NewsService_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _NewsService_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _NewsService_Update_Handler,
		},
		{
			MethodName: "List",
			Handler:    _NewsService_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/amikhailau/users-service/pkg/pb/service.proto",
}
