// Code generated by protoc-gen-go. DO NOT EDIT.
// source: github.com/amikhailau/users-service/pkg/pb/service.proto

package pb

import (
	context "context"
	fmt "fmt"
	math "math"

	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	proto "github.com/golang/protobuf/proto"
	empty "github.com/golang/protobuf/ptypes/empty"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	query "github.com/infobloxopen/atlas-app-toolkit/query"
	resource "github.com/infobloxopen/atlas-app-toolkit/rpc/resource"
	_ "github.com/infobloxopen/protoc-gen-atlas-query-validate/options"
	_ "github.com/infobloxopen/protoc-gen-atlas-validate/options"
	_ "github.com/infobloxopen/protoc-gen-gorm/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	field_mask "google.golang.org/genproto/protobuf/field_mask"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// TODO: Structure your own protobuf messages. Each protocol buffer message is a
// small logical record of information, containing a series of name-value pairs.
type VersionResponse struct {
	Version              string   `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VersionResponse) Reset()         { *m = VersionResponse{} }
func (m *VersionResponse) String() string { return proto.CompactTextString(m) }
func (*VersionResponse) ProtoMessage()    {}
func (*VersionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{0}
}

func (m *VersionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VersionResponse.Unmarshal(m, b)
}
func (m *VersionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VersionResponse.Marshal(b, m, deterministic)
}
func (m *VersionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VersionResponse.Merge(m, src)
}
func (m *VersionResponse) XXX_Size() int {
	return xxx_messageInfo_VersionResponse.Size(m)
}
func (m *VersionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VersionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VersionResponse proto.InternalMessageInfo

func (m *VersionResponse) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

type User struct {
	// The User identifier.
	Id *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the User
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The description of the User
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{1}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateUserRequest struct {
	Payload              *User    `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{2}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetPayload() *User {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateUserResponse struct {
	Result               *User    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{3}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetResult() *User {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadUserRequest struct {
	Id                   *resource.Identifier  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReadUserRequest) Reset()         { *m = ReadUserRequest{} }
func (m *ReadUserRequest) String() string { return proto.CompactTextString(m) }
func (*ReadUserRequest) ProtoMessage()    {}
func (*ReadUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{4}
}

func (m *ReadUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserRequest.Unmarshal(m, b)
}
func (m *ReadUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserRequest.Marshal(b, m, deterministic)
}
func (m *ReadUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserRequest.Merge(m, src)
}
func (m *ReadUserRequest) XXX_Size() int {
	return xxx_messageInfo_ReadUserRequest.Size(m)
}
func (m *ReadUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserRequest proto.InternalMessageInfo

func (m *ReadUserRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ReadUserRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ReadUserResponse struct {
	Result               *User    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadUserResponse) Reset()         { *m = ReadUserResponse{} }
func (m *ReadUserResponse) String() string { return proto.CompactTextString(m) }
func (*ReadUserResponse) ProtoMessage()    {}
func (*ReadUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{5}
}

func (m *ReadUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadUserResponse.Unmarshal(m, b)
}
func (m *ReadUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadUserResponse.Marshal(b, m, deterministic)
}
func (m *ReadUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadUserResponse.Merge(m, src)
}
func (m *ReadUserResponse) XXX_Size() int {
	return xxx_messageInfo_ReadUserResponse.Size(m)
}
func (m *ReadUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadUserResponse proto.InternalMessageInfo

func (m *ReadUserResponse) GetResult() *User {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateUserRequest struct {
	Payload              *User                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Fields               *field_mask.FieldMask `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{6}
}

func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (m *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(m, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetPayload() *User {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UpdateUserRequest) GetFields() *field_mask.FieldMask {
	if m != nil {
		return m.Fields
	}
	return nil
}

type UpdateUserResponse struct {
	Result               *User    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateUserResponse) Reset()         { *m = UpdateUserResponse{} }
func (m *UpdateUserResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateUserResponse) ProtoMessage()    {}
func (*UpdateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{7}
}

func (m *UpdateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserResponse.Unmarshal(m, b)
}
func (m *UpdateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserResponse.Marshal(b, m, deterministic)
}
func (m *UpdateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserResponse.Merge(m, src)
}
func (m *UpdateUserResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateUserResponse.Size(m)
}
func (m *UpdateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserResponse proto.InternalMessageInfo

func (m *UpdateUserResponse) GetResult() *User {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteUserRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{8}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeleteUserResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResponse) Reset()         { *m = DeleteUserResponse{} }
func (m *DeleteUserResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResponse) ProtoMessage()    {}
func (*DeleteUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{9}
}

func (m *DeleteUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResponse.Unmarshal(m, b)
}
func (m *DeleteUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResponse.Marshal(b, m, deterministic)
}
func (m *DeleteUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResponse.Merge(m, src)
}
func (m *DeleteUserResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResponse.Size(m)
}
func (m *DeleteUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResponse proto.InternalMessageInfo

type ListUserRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListUserRequest) Reset()         { *m = ListUserRequest{} }
func (m *ListUserRequest) String() string { return proto.CompactTextString(m) }
func (*ListUserRequest) ProtoMessage()    {}
func (*ListUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{10}
}

func (m *ListUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUserRequest.Unmarshal(m, b)
}
func (m *ListUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUserRequest.Marshal(b, m, deterministic)
}
func (m *ListUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUserRequest.Merge(m, src)
}
func (m *ListUserRequest) XXX_Size() int {
	return xxx_messageInfo_ListUserRequest.Size(m)
}
func (m *ListUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUserRequest proto.InternalMessageInfo

func (m *ListUserRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListUserRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListUserRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListUserRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListUsersResponse struct {
	Results              []*User         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Page                 *query.PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{11}
}

func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (m *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(m, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetResults() []*User {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ListUsersResponse) GetPage() *query.PageInfo {
	if m != nil {
		return m.Page
	}
	return nil
}

type Item struct {
	// The Item identifier.
	Id *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the Item
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// The description of the Item
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Item) Reset()         { *m = Item{} }
func (m *Item) String() string { return proto.CompactTextString(m) }
func (*Item) ProtoMessage()    {}
func (*Item) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{12}
}

func (m *Item) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Item.Unmarshal(m, b)
}
func (m *Item) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Item.Marshal(b, m, deterministic)
}
func (m *Item) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Item.Merge(m, src)
}
func (m *Item) XXX_Size() int {
	return xxx_messageInfo_Item.Size(m)
}
func (m *Item) XXX_DiscardUnknown() {
	xxx_messageInfo_Item.DiscardUnknown(m)
}

var xxx_messageInfo_Item proto.InternalMessageInfo

func (m *Item) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Item) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Item) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

type CreateItemRequest struct {
	Payload              *Item    `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateItemRequest) Reset()         { *m = CreateItemRequest{} }
func (m *CreateItemRequest) String() string { return proto.CompactTextString(m) }
func (*CreateItemRequest) ProtoMessage()    {}
func (*CreateItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{13}
}

func (m *CreateItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateItemRequest.Unmarshal(m, b)
}
func (m *CreateItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateItemRequest.Marshal(b, m, deterministic)
}
func (m *CreateItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateItemRequest.Merge(m, src)
}
func (m *CreateItemRequest) XXX_Size() int {
	return xxx_messageInfo_CreateItemRequest.Size(m)
}
func (m *CreateItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateItemRequest proto.InternalMessageInfo

func (m *CreateItemRequest) GetPayload() *Item {
	if m != nil {
		return m.Payload
	}
	return nil
}

type CreateItemResponse struct {
	Result               *Item    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateItemResponse) Reset()         { *m = CreateItemResponse{} }
func (m *CreateItemResponse) String() string { return proto.CompactTextString(m) }
func (*CreateItemResponse) ProtoMessage()    {}
func (*CreateItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{14}
}

func (m *CreateItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateItemResponse.Unmarshal(m, b)
}
func (m *CreateItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateItemResponse.Marshal(b, m, deterministic)
}
func (m *CreateItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateItemResponse.Merge(m, src)
}
func (m *CreateItemResponse) XXX_Size() int {
	return xxx_messageInfo_CreateItemResponse.Size(m)
}
func (m *CreateItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateItemResponse proto.InternalMessageInfo

func (m *CreateItemResponse) GetResult() *Item {
	if m != nil {
		return m.Result
	}
	return nil
}

type ReadItemRequest struct {
	Id                   *resource.Identifier  `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReadItemRequest) Reset()         { *m = ReadItemRequest{} }
func (m *ReadItemRequest) String() string { return proto.CompactTextString(m) }
func (*ReadItemRequest) ProtoMessage()    {}
func (*ReadItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{15}
}

func (m *ReadItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadItemRequest.Unmarshal(m, b)
}
func (m *ReadItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadItemRequest.Marshal(b, m, deterministic)
}
func (m *ReadItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadItemRequest.Merge(m, src)
}
func (m *ReadItemRequest) XXX_Size() int {
	return xxx_messageInfo_ReadItemRequest.Size(m)
}
func (m *ReadItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReadItemRequest proto.InternalMessageInfo

func (m *ReadItemRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *ReadItemRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

type ReadItemResponse struct {
	Result               *Item    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReadItemResponse) Reset()         { *m = ReadItemResponse{} }
func (m *ReadItemResponse) String() string { return proto.CompactTextString(m) }
func (*ReadItemResponse) ProtoMessage()    {}
func (*ReadItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{16}
}

func (m *ReadItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReadItemResponse.Unmarshal(m, b)
}
func (m *ReadItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReadItemResponse.Marshal(b, m, deterministic)
}
func (m *ReadItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReadItemResponse.Merge(m, src)
}
func (m *ReadItemResponse) XXX_Size() int {
	return xxx_messageInfo_ReadItemResponse.Size(m)
}
func (m *ReadItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReadItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReadItemResponse proto.InternalMessageInfo

func (m *ReadItemResponse) GetResult() *Item {
	if m != nil {
		return m.Result
	}
	return nil
}

type UpdateItemRequest struct {
	Payload              *Item                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	Fields               *field_mask.FieldMask `protobuf:"bytes,2,opt,name=fields,proto3" json:"fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateItemRequest) Reset()         { *m = UpdateItemRequest{} }
func (m *UpdateItemRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateItemRequest) ProtoMessage()    {}
func (*UpdateItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{17}
}

func (m *UpdateItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemRequest.Unmarshal(m, b)
}
func (m *UpdateItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemRequest.Marshal(b, m, deterministic)
}
func (m *UpdateItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemRequest.Merge(m, src)
}
func (m *UpdateItemRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateItemRequest.Size(m)
}
func (m *UpdateItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemRequest proto.InternalMessageInfo

func (m *UpdateItemRequest) GetPayload() *Item {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *UpdateItemRequest) GetFields() *field_mask.FieldMask {
	if m != nil {
		return m.Fields
	}
	return nil
}

type UpdateItemResponse struct {
	Result               *Item    `protobuf:"bytes,1,opt,name=result,proto3" json:"result,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateItemResponse) Reset()         { *m = UpdateItemResponse{} }
func (m *UpdateItemResponse) String() string { return proto.CompactTextString(m) }
func (*UpdateItemResponse) ProtoMessage()    {}
func (*UpdateItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{18}
}

func (m *UpdateItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateItemResponse.Unmarshal(m, b)
}
func (m *UpdateItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateItemResponse.Marshal(b, m, deterministic)
}
func (m *UpdateItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateItemResponse.Merge(m, src)
}
func (m *UpdateItemResponse) XXX_Size() int {
	return xxx_messageInfo_UpdateItemResponse.Size(m)
}
func (m *UpdateItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateItemResponse proto.InternalMessageInfo

func (m *UpdateItemResponse) GetResult() *Item {
	if m != nil {
		return m.Result
	}
	return nil
}

type DeleteItemRequest struct {
	Id                   *resource.Identifier `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *DeleteItemRequest) Reset()         { *m = DeleteItemRequest{} }
func (m *DeleteItemRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteItemRequest) ProtoMessage()    {}
func (*DeleteItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{19}
}

func (m *DeleteItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteItemRequest.Unmarshal(m, b)
}
func (m *DeleteItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteItemRequest.Marshal(b, m, deterministic)
}
func (m *DeleteItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteItemRequest.Merge(m, src)
}
func (m *DeleteItemRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteItemRequest.Size(m)
}
func (m *DeleteItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteItemRequest proto.InternalMessageInfo

func (m *DeleteItemRequest) GetId() *resource.Identifier {
	if m != nil {
		return m.Id
	}
	return nil
}

type DeleteItemResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteItemResponse) Reset()         { *m = DeleteItemResponse{} }
func (m *DeleteItemResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteItemResponse) ProtoMessage()    {}
func (*DeleteItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{20}
}

func (m *DeleteItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteItemResponse.Unmarshal(m, b)
}
func (m *DeleteItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteItemResponse.Marshal(b, m, deterministic)
}
func (m *DeleteItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteItemResponse.Merge(m, src)
}
func (m *DeleteItemResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteItemResponse.Size(m)
}
func (m *DeleteItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteItemResponse proto.InternalMessageInfo

type ListItemRequest struct {
	Filter               *query.Filtering      `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	OrderBy              *query.Sorting        `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	Fields               *query.FieldSelection `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	Paging               *query.Pagination     `protobuf:"bytes,4,opt,name=paging,proto3" json:"paging,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ListItemRequest) Reset()         { *m = ListItemRequest{} }
func (m *ListItemRequest) String() string { return proto.CompactTextString(m) }
func (*ListItemRequest) ProtoMessage()    {}
func (*ListItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{21}
}

func (m *ListItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListItemRequest.Unmarshal(m, b)
}
func (m *ListItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListItemRequest.Marshal(b, m, deterministic)
}
func (m *ListItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListItemRequest.Merge(m, src)
}
func (m *ListItemRequest) XXX_Size() int {
	return xxx_messageInfo_ListItemRequest.Size(m)
}
func (m *ListItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListItemRequest proto.InternalMessageInfo

func (m *ListItemRequest) GetFilter() *query.Filtering {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (m *ListItemRequest) GetOrderBy() *query.Sorting {
	if m != nil {
		return m.OrderBy
	}
	return nil
}

func (m *ListItemRequest) GetFields() *query.FieldSelection {
	if m != nil {
		return m.Fields
	}
	return nil
}

func (m *ListItemRequest) GetPaging() *query.Pagination {
	if m != nil {
		return m.Paging
	}
	return nil
}

type ListItemsResponse struct {
	Results              []*Item         `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	Page                 *query.PageInfo `protobuf:"bytes,2,opt,name=page,proto3" json:"page,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ListItemsResponse) Reset()         { *m = ListItemsResponse{} }
func (m *ListItemsResponse) String() string { return proto.CompactTextString(m) }
func (*ListItemsResponse) ProtoMessage()    {}
func (*ListItemsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_b1742b9f6e5341e0, []int{22}
}

func (m *ListItemsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListItemsResponse.Unmarshal(m, b)
}
func (m *ListItemsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListItemsResponse.Marshal(b, m, deterministic)
}
func (m *ListItemsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListItemsResponse.Merge(m, src)
}
func (m *ListItemsResponse) XXX_Size() int {
	return xxx_messageInfo_ListItemsResponse.Size(m)
}
func (m *ListItemsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListItemsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListItemsResponse proto.InternalMessageInfo

func (m *ListItemsResponse) GetResults() []*Item {
	if m != nil {
		return m.Results
	}
	return nil
}

func (m *ListItemsResponse) GetPage() *query.PageInfo {
	if m != nil {
		return m.Page
	}
	return nil
}

func init() {
	proto.RegisterType((*VersionResponse)(nil), "service.VersionResponse")
	proto.RegisterType((*User)(nil), "service.User")
	proto.RegisterType((*CreateUserRequest)(nil), "service.CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "service.CreateUserResponse")
	proto.RegisterType((*ReadUserRequest)(nil), "service.ReadUserRequest")
	proto.RegisterType((*ReadUserResponse)(nil), "service.ReadUserResponse")
	proto.RegisterType((*UpdateUserRequest)(nil), "service.UpdateUserRequest")
	proto.RegisterType((*UpdateUserResponse)(nil), "service.UpdateUserResponse")
	proto.RegisterType((*DeleteUserRequest)(nil), "service.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResponse)(nil), "service.DeleteUserResponse")
	proto.RegisterType((*ListUserRequest)(nil), "service.ListUserRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "service.ListUsersResponse")
	proto.RegisterType((*Item)(nil), "service.Item")
	proto.RegisterType((*CreateItemRequest)(nil), "service.CreateItemRequest")
	proto.RegisterType((*CreateItemResponse)(nil), "service.CreateItemResponse")
	proto.RegisterType((*ReadItemRequest)(nil), "service.ReadItemRequest")
	proto.RegisterType((*ReadItemResponse)(nil), "service.ReadItemResponse")
	proto.RegisterType((*UpdateItemRequest)(nil), "service.UpdateItemRequest")
	proto.RegisterType((*UpdateItemResponse)(nil), "service.UpdateItemResponse")
	proto.RegisterType((*DeleteItemRequest)(nil), "service.DeleteItemRequest")
	proto.RegisterType((*DeleteItemResponse)(nil), "service.DeleteItemResponse")
	proto.RegisterType((*ListItemRequest)(nil), "service.ListItemRequest")
	proto.RegisterType((*ListItemsResponse)(nil), "service.ListItemsResponse")
}

func init() {
	proto.RegisterFile("github.com/amikhailau/users-service/pkg/pb/service.proto", fileDescriptor_b1742b9f6e5341e0)
}

var fileDescriptor_b1742b9f6e5341e0 = []byte{
	// 1073 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x57, 0x41, 0x6f, 0x1b, 0x45,
	0x14, 0x8e, 0x13, 0xe3, 0x98, 0x49, 0x21, 0xc9, 0x88, 0x36, 0xf6, 0xb6, 0x52, 0xa3, 0x95, 0xaa,
	0x96, 0x80, 0x77, 0x2b, 0x83, 0x04, 0x24, 0x5c, 0x08, 0x14, 0x14, 0x54, 0x50, 0xe5, 0xd0, 0x1e,
	0x22, 0xa4, 0x30, 0xf6, 0xbe, 0x6c, 0x46, 0x59, 0xef, 0x4c, 0x67, 0xd6, 0xa1, 0x16, 0x42, 0x48,
	0xfc, 0x05, 0x7e, 0x03, 0x67, 0xce, 0xc9, 0x85, 0x1f, 0xc1, 0x0d, 0x71, 0xe4, 0x87, 0xa0, 0x9d,
	0x99, 0x5d, 0x4f, 0x76, 0x37, 0xcd, 0xc6, 0x48, 0x08, 0xf5, 0xe6, 0x9d, 0xf7, 0xde, 0xf7, 0xbe,
	0xf7, 0xe6, 0x7b, 0x33, 0x63, 0xf4, 0x61, 0x48, 0x93, 0xe3, 0xc9, 0xd0, 0x1b, 0xb1, 0xb1, 0x4f,
	0xc6, 0xf4, 0xe4, 0x98, 0xd0, 0x88, 0x4c, 0xfc, 0x89, 0x04, 0x21, 0x7b, 0x12, 0xc4, 0x29, 0x1d,
	0x81, 0xcf, 0x4f, 0x42, 0x9f, 0x0f, 0x7d, 0xf3, 0xe9, 0x71, 0xc1, 0x12, 0x86, 0x97, 0xcd, 0xa7,
	0x73, 0x3b, 0x64, 0x2c, 0x8c, 0xc0, 0x57, 0xcb, 0xc3, 0xc9, 0x91, 0x0f, 0x63, 0x9e, 0x4c, 0xb5,
	0x97, 0x73, 0xc7, 0x18, 0x09, 0xa7, 0x3e, 0x89, 0x63, 0x96, 0x90, 0x84, 0xb2, 0x58, 0x1a, 0xeb,
	0x27, 0x56, 0x76, 0x88, 0x4f, 0xd9, 0x94, 0x0b, 0xf6, 0x62, 0xaa, 0x91, 0x46, 0xbd, 0x10, 0xe2,
	0xde, 0x29, 0x89, 0x68, 0x40, 0x12, 0xf0, 0x4b, 0x3f, 0x0c, 0xc4, 0xbb, 0x96, 0xb3, 0xfc, 0x9e,
	0x84, 0x21, 0x08, 0x9f, 0x71, 0x95, 0xa4, 0x22, 0xe1, 0xb6, 0x95, 0x90, 0xc6, 0x47, 0x6c, 0x18,
	0xb1, 0x17, 0x8c, 0x43, 0x6c, 0xa7, 0x0c, 0x99, 0x18, 0xe7, 0x10, 0xe9, 0x87, 0x89, 0xdd, 0x2c,
	0xd6, 0x79, 0x44, 0x21, 0x0a, 0x0e, 0xc7, 0x44, 0x9e, 0x18, 0x8f, 0x2f, 0x2f, 0x43, 0x27, 0x49,
	0x44, 0x64, 0x8f, 0x70, 0xde, 0x4b, 0x18, 0x8b, 0x4e, 0x68, 0xe2, 0x3f, 0x9f, 0x80, 0x98, 0xfa,
	0x23, 0x16, 0x45, 0x30, 0x4a, 0x33, 0x1d, 0x32, 0x0e, 0x82, 0x24, 0x4c, 0x64, 0x4c, 0x1f, 0xd5,
	0xc7, 0x12, 0x7c, 0xe4, 0x0b, 0x90, 0x6c, 0x22, 0x46, 0x90, 0xff, 0x30, 0x30, 0xdf, 0xd4, 0x28,
	0x58, 0x23, 0x2a, 0x46, 0xb3, 0x7e, 0x67, 0x0d, 0x50, 0xcb, 0x87, 0x85, 0xa6, 0x7f, 0x5d, 0x1b,
	0xb5, 0x84, 0xa7, 0x96, 0x0b, 0x78, 0xee, 0x3b, 0x68, 0xf5, 0x19, 0x08, 0x49, 0x59, 0x3c, 0x00,
	0xc9, 0x59, 0x2c, 0x01, 0x77, 0xd0, 0xf2, 0xa9, 0x5e, 0xea, 0x34, 0x36, 0x1b, 0x0f, 0x5e, 0x1f,
	0x64, 0x9f, 0xee, 0x4f, 0xa8, 0xf9, 0x54, 0x82, 0xc0, 0x1f, 0xa0, 0x45, 0x1a, 0x28, 0xe3, 0x4a,
	0xff, 0xa6, 0xa7, 0x70, 0x3d, 0xc1, 0x47, 0xde, 0x5e, 0x00, 0x71, 0x42, 0x8f, 0x28, 0x88, 0xdd,
	0xb5, 0xf3, 0xb3, 0xee, 0x0d, 0x84, 0x70, 0x4b, 0x82, 0xa0, 0x24, 0x7a, 0xd0, 0x18, 0x2c, 0xd2,
	0x00, 0x63, 0xd4, 0x8c, 0xc9, 0x18, 0x3a, 0x8b, 0x0a, 0x57, 0xfd, 0xc6, 0x9b, 0x68, 0x25, 0x00,
	0x39, 0x12, 0x54, 0xd1, 0xec, 0x2c, 0x29, 0x93, 0xbd, 0xb4, 0xdd, 0x3e, 0x3f, 0xeb, 0x36, 0xdb,
	0x8d, 0xcd, 0x05, 0xf7, 0x63, 0xb4, 0xfe, 0xa9, 0x00, 0x92, 0x40, 0x4a, 0x63, 0x00, 0xcf, 0x27,
	0x20, 0x13, 0x7c, 0x1f, 0x2d, 0x73, 0x32, 0x8d, 0x18, 0xc9, 0x28, 0xbd, 0xe1, 0x65, 0xf3, 0xa2,
	0xdc, 0x32, 0xab, 0xbb, 0x83, 0xb0, 0x1d, 0x6d, 0xca, 0xbd, 0x87, 0x5a, 0x02, 0xe4, 0x24, 0x4a,
	0xaa, 0xa3, 0x8d, 0xd1, 0x8d, 0xd1, 0xea, 0x00, 0x48, 0x60, 0x27, 0xbe, 0x77, 0x65, 0x1b, 0x54,
	0xd1, 0xef, 0xa3, 0x96, 0xd2, 0xab, 0x54, 0x65, 0xaf, 0xf4, 0xef, 0x78, 0xd9, 0xc6, 0x79, 0x84,
	0x53, 0xef, 0xf3, 0xd4, 0xb6, 0x0f, 0x46, 0x8d, 0x03, 0xe3, 0xeb, 0x7e, 0x84, 0xd6, 0x66, 0xf9,
	0xae, 0x47, 0x95, 0xa3, 0xf5, 0xa7, 0x3c, 0x98, 0xb3, 0x4b, 0xb8, 0x5f, 0xa0, 0xeb, 0x78, 0x7a,
	0xfa, 0xbc, 0x6c, 0xfa, 0x34, 0xe3, 0xaf, 0x88, 0x3c, 0xc9, 0xc9, 0xee, 0x20, 0x6c, 0x67, 0xbc,
	0x1e, 0xdd, 0x6d, 0xb4, 0xfe, 0x19, 0x44, 0x70, 0x91, 0x6e, 0xbd, 0xde, 0xba, 0x6f, 0x21, 0x6c,
	0xc7, 0xea, 0xc4, 0xee, 0x5f, 0x0d, 0xb4, 0xfa, 0x98, 0xca, 0xc4, 0x06, 0xf4, 0xd3, 0xb2, 0xa2,
	0x04, 0x84, 0x01, 0xdd, 0x28, 0xee, 0x42, 0x6a, 0xa3, 0x71, 0x38, 0x30, 0x6e, 0xf8, 0x21, 0x6a,
	0x33, 0x11, 0x80, 0x38, 0x1c, 0x4e, 0x4d, 0x27, 0x6e, 0x5e, 0x0c, 0xd9, 0x67, 0x22, 0x49, 0x03,
	0x96, 0x95, 0xdb, 0xee, 0xd4, 0xda, 0xe8, 0xa5, 0xfa, 0x1b, 0x8d, 0x1f, 0xa2, 0x16, 0x27, 0x21,
	0x8d, 0xc3, 0x4e, 0x53, 0x45, 0x75, 0x2e, 0x46, 0x3d, 0x49, 0x6d, 0x44, 0x47, 0x68, 0x3f, 0xf7,
	0x18, 0xad, 0x67, 0xd5, 0xc9, 0xbc, 0xd9, 0xf7, 0xd1, 0xb2, 0xee, 0xa7, 0xec, 0x34, 0x36, 0x97,
	0x2a, 0xf6, 0xd7, 0x58, 0xf1, 0x16, 0x6a, 0x72, 0x12, 0x82, 0xa9, 0xe9, 0x56, 0x29, 0x1b, 0xec,
	0xc5, 0x47, 0x6c, 0xa0, 0x7c, 0xd2, 0x81, 0xdf, 0x4b, 0x60, 0xfc, 0x3f, 0x18, 0xf8, 0x94, 0x46,
	0x0d, 0x29, 0x2b, 0xb7, 0xf2, 0xc0, 0xeb, 0xe8, 0x2b, 0x65, 0xa9, 0xdc, 0x0a, 0x03, 0x6f, 0x27,
	0xfe, 0x2f, 0x06, 0x7e, 0x1e, 0xaa, 0xf9, 0xc0, 0xcf, 0xd3, 0xa5, 0x7f, 0x37, 0xf0, 0xf3, 0xd0,
	0xcd, 0x07, 0xfe, 0xfa, 0xbd, 0x9d, 0x0d, 0xbc, 0x9d, 0x38, 0x1f, 0x78, 0x1b, 0xf0, 0xd5, 0x1b,
	0xf8, 0xb4, 0xba, 0x5a, 0x03, 0xaf, 0xf7, 0x77, 0x8e, 0x81, 0xef, 0x7f, 0x87, 0x6e, 0xa8, 0x63,
	0x65, 0x5f, 0x23, 0xe1, 0x27, 0x08, 0x7d, 0x01, 0x89, 0x79, 0x21, 0xe0, 0x5b, 0x25, 0x65, 0x3c,
	0x4a, 0x1f, 0x9c, 0x4e, 0x27, 0xcf, 0x5c, 0x78, 0x4b, 0xb8, 0x6b, 0x3f, 0xff, 0xf1, 0xf7, 0x2f,
	0x8b, 0x08, 0xb7, 0x7d, 0xf3, 0x86, 0xe8, 0xff, 0xd6, 0x44, 0xaf, 0xa9, 0x14, 0xf8, 0x00, 0xb5,
	0xf4, 0x74, 0x62, 0x27, 0x8f, 0x2f, 0xdd, 0xee, 0xce, 0xed, 0x4a, 0x9b, 0x81, 0xdf, 0x50, 0xf0,
	0xeb, 0x6e, 0x4b, 0x3f, 0x9b, 0xb7, 0x73, 0x4d, 0x7f, 0x8b, 0x9a, 0xe9, 0x30, 0xe1, 0x19, 0xb3,
	0xc2, 0xe5, 0xed, 0x74, 0x2b, 0x2c, 0x06, 0xf5, 0xae, 0x42, 0xed, 0xe2, 0x0d, 0x8d, 0xea, 0xff,
	0x40, 0x03, 0x2f, 0x7b, 0xdc, 0x1d, 0xd2, 0xe0, 0x47, 0xfc, 0x6b, 0x03, 0xb5, 0xb4, 0xfc, 0x2d,
	0xea, 0xa5, 0x2b, 0xd7, 0xa2, 0x5e, 0xbe, 0x1c, 0xdd, 0xe1, 0x9f, 0xbf, 0x77, 0x17, 0xdb, 0x0b,
	0x2a, 0xd5, 0x33, 0xe7, 0x6e, 0x96, 0xca, 0x14, 0xe0, 0x15, 0x52, 0xe6, 0x95, 0x1d, 0x6c, 0xf5,
	0x6b, 0xfb, 0xe2, 0x08, 0xb5, 0xf4, 0xb0, 0x58, 0x34, 0x4b, 0x57, 0xad, 0x45, 0xb3, 0xe2, 0x2a,
	0x7d, 0xfb, 0xfc, 0xac, 0xdb, 0xd2, 0xcf, 0x3e, 0xdd, 0x95, 0xad, 0x4b, 0xbb, 0xf2, 0x18, 0x35,
	0x53, 0x95, 0x5a, 0x3d, 0x2f, 0xdc, 0xc1, 0x8e, 0x53, 0xb2, 0xe4, 0x72, 0x76, 0xdf, 0x54, 0xf0,
	0x6d, 0x6c, 0xb6, 0xd2, 0x31, 0x77, 0xc0, 0xda, 0x82, 0x52, 0x8c, 0x92, 0xfe, 0x4b, 0x14, 0x63,
	0x0d, 0x7e, 0x49, 0x31, 0x17, 0x4e, 0x8a, 0x99, 0x62, 0x68, 0x0a, 0x79, 0x95, 0x62, 0x6c, 0xdc,
	0x6e, 0x85, 0xa5, 0xa4, 0x18, 0x85, 0x7a, 0x2d, 0xc5, 0x54, 0x53, 0x2f, 0x9f, 0xae, 0x25, 0xc5,
	0x98, 0x54, 0xb5, 0x14, 0x53, 0xd3, 0xf7, 0x25, 0x8a, 0xa9, 0xa6, 0x59, 0x71, 0x16, 0x1b, 0xc5,
	0xa4, 0x6b, 0xb9, 0x62, 0x2e, 0xe9, 0x4a, 0xb5, 0x62, 0xec, 0x4c, 0x4e, 0xc9, 0x52, 0xa5, 0x18,
	0x05, 0x3f, 0x53, 0xcc, 0xae, 0x7f, 0xd0, 0xab, 0xff, 0xe7, 0x7a, 0x87, 0x0f, 0x87, 0x2d, 0x75,
	0xa0, 0xbd, 0xf7, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x0f, 0xd4, 0x56, 0x07, 0x94, 0x0f, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UsersServiceClient is the client API for UsersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersServiceClient interface {
	GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error)
}

type usersServiceClient struct {
	cc *grpc.ClientConn
}

func NewUsersServiceClient(cc *grpc.ClientConn) UsersServiceClient {
	return &usersServiceClient{cc}
}

func (c *usersServiceClient) GetVersion(ctx context.Context, in *empty.Empty, opts ...grpc.CallOption) (*VersionResponse, error) {
	out := new(VersionResponse)
	err := c.cc.Invoke(ctx, "/service.UsersService/GetVersion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServiceServer is the server API for UsersService service.
type UsersServiceServer interface {
	GetVersion(context.Context, *empty.Empty) (*VersionResponse, error)
}

func RegisterUsersServiceServer(s *grpc.Server, srv UsersServiceServer) {
	s.RegisterService(&_UsersService_serviceDesc, srv)
}

func _UsersService_GetVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(empty.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServiceServer).GetVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.UsersService/GetVersion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServiceServer).GetVersion(ctx, req.(*empty.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _UsersService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.UsersService",
	HandlerType: (*UsersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetVersion",
			Handler:    _UsersService_GetVersion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/amikhailau/users-service/pkg/pb/service.proto",
}

// UsersClient is the client API for Users service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UsersClient interface {
	// Use this method to create a User information.
	Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error)
	// Use this method to read a User information by identifier.
	Read(ctx context.Context, in *ReadUserRequest, opts ...grpc.CallOption) (*ReadUserResponse, error)
	// Use this method to update a User information.
	Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error)
	// Use this method to delete a particular User.
	Delete(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error)
	// Use this method to retrieve all the Users.
	List(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
}

type usersClient struct {
	cc *grpc.ClientConn
}

func NewUsersClient(cc *grpc.ClientConn) UsersClient {
	return &usersClient{cc}
}

func (c *usersClient) Create(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*CreateUserResponse, error) {
	out := new(CreateUserResponse)
	err := c.cc.Invoke(ctx, "/service.Users/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Read(ctx context.Context, in *ReadUserRequest, opts ...grpc.CallOption) (*ReadUserResponse, error) {
	out := new(ReadUserResponse)
	err := c.cc.Invoke(ctx, "/service.Users/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Update(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*UpdateUserResponse, error) {
	out := new(UpdateUserResponse)
	err := c.cc.Invoke(ctx, "/service.Users/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) Delete(ctx context.Context, in *DeleteUserRequest, opts ...grpc.CallOption) (*DeleteUserResponse, error) {
	out := new(DeleteUserResponse)
	err := c.cc.Invoke(ctx, "/service.Users/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *usersClient) List(ctx context.Context, in *ListUserRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/service.Users/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UsersServer is the server API for Users service.
type UsersServer interface {
	// Use this method to create a User information.
	Create(context.Context, *CreateUserRequest) (*CreateUserResponse, error)
	// Use this method to read a User information by identifier.
	Read(context.Context, *ReadUserRequest) (*ReadUserResponse, error)
	// Use this method to update a User information.
	Update(context.Context, *UpdateUserRequest) (*UpdateUserResponse, error)
	// Use this method to delete a particular User.
	Delete(context.Context, *DeleteUserRequest) (*DeleteUserResponse, error)
	// Use this method to retrieve all the Users.
	List(context.Context, *ListUserRequest) (*ListUsersResponse, error)
}

func RegisterUsersServer(s *grpc.Server, srv UsersServer) {
	s.RegisterService(&_Users_serviceDesc, srv)
}

func _Users_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Users/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Create(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Users/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Read(ctx, req.(*ReadUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Users/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Update(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Users/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).Delete(ctx, req.(*DeleteUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Users_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UsersServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Users/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UsersServer).List(ctx, req.(*ListUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Users_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Users",
	HandlerType: (*UsersServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Users_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Users_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Users_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Users_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Users_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/amikhailau/users-service/pkg/pb/service.proto",
}

// ItemsClient is the client API for Items service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ItemsClient interface {
	// Use this method to create a Item information.
	Create(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*CreateItemResponse, error)
	// Use this method to read a Item information by identifier.
	Read(ctx context.Context, in *ReadItemRequest, opts ...grpc.CallOption) (*ReadItemResponse, error)
	// Use this method to update a Item information.
	Update(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*UpdateItemResponse, error)
	// Use this method to delete a particular Item.
	Delete(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*DeleteItemResponse, error)
	// Use this method to retrieve all the Items.
	List(ctx context.Context, in *ListItemRequest, opts ...grpc.CallOption) (*ListItemsResponse, error)
}

type itemsClient struct {
	cc *grpc.ClientConn
}

func NewItemsClient(cc *grpc.ClientConn) ItemsClient {
	return &itemsClient{cc}
}

func (c *itemsClient) Create(ctx context.Context, in *CreateItemRequest, opts ...grpc.CallOption) (*CreateItemResponse, error) {
	out := new(CreateItemResponse)
	err := c.cc.Invoke(ctx, "/service.Items/Create", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsClient) Read(ctx context.Context, in *ReadItemRequest, opts ...grpc.CallOption) (*ReadItemResponse, error) {
	out := new(ReadItemResponse)
	err := c.cc.Invoke(ctx, "/service.Items/Read", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsClient) Update(ctx context.Context, in *UpdateItemRequest, opts ...grpc.CallOption) (*UpdateItemResponse, error) {
	out := new(UpdateItemResponse)
	err := c.cc.Invoke(ctx, "/service.Items/Update", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsClient) Delete(ctx context.Context, in *DeleteItemRequest, opts ...grpc.CallOption) (*DeleteItemResponse, error) {
	out := new(DeleteItemResponse)
	err := c.cc.Invoke(ctx, "/service.Items/Delete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *itemsClient) List(ctx context.Context, in *ListItemRequest, opts ...grpc.CallOption) (*ListItemsResponse, error) {
	out := new(ListItemsResponse)
	err := c.cc.Invoke(ctx, "/service.Items/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ItemsServer is the server API for Items service.
type ItemsServer interface {
	// Use this method to create a Item information.
	Create(context.Context, *CreateItemRequest) (*CreateItemResponse, error)
	// Use this method to read a Item information by identifier.
	Read(context.Context, *ReadItemRequest) (*ReadItemResponse, error)
	// Use this method to update a Item information.
	Update(context.Context, *UpdateItemRequest) (*UpdateItemResponse, error)
	// Use this method to delete a particular Item.
	Delete(context.Context, *DeleteItemRequest) (*DeleteItemResponse, error)
	// Use this method to retrieve all the Items.
	List(context.Context, *ListItemRequest) (*ListItemsResponse, error)
}

func RegisterItemsServer(s *grpc.Server, srv ItemsServer) {
	s.RegisterService(&_Items_serviceDesc, srv)
}

func _Items_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Items/Create",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServer).Create(ctx, req.(*CreateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Items_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Items/Read",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServer).Read(ctx, req.(*ReadItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Items_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Items/Update",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServer).Update(ctx, req.(*UpdateItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Items_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Items/Delete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServer).Delete(ctx, req.(*DeleteItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Items_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListItemRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ItemsServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Items/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ItemsServer).List(ctx, req.(*ListItemRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Items_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Items",
	HandlerType: (*ItemsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _Items_Create_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _Items_Read_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _Items_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _Items_Delete_Handler,
		},
		{
			MethodName: "List",
			Handler:    _Items_List_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "github.com/amikhailau/users-service/pkg/pb/service.proto",
}
